namespace Zava.Api.Services;

using Zava.Api.Models;

public static class CosmeticsSeeder
{
    public static List<Category> GenerateCategories()
    {
        return new List<Category>
        {
            new() { Id = 1, Name = "Parfums Femme", NameEn = "Women's Fragrances", Description = "Eaux de parfum et eaux de toilette femme", DescriptionEn = "Women's eau de parfum and eau de toilette", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "Spa" },
            new() { Id = 2, Name = "Parfums Homme", NameEn = "Men's Fragrances", Description = "Eaux de parfum et eaux de toilette homme", DescriptionEn = "Men's eau de parfum and eau de toilette", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "Face" },
            new() { Id = 3, Name = "Maquillage Lèvres", NameEn = "Lip Makeup", Description = "Rouges à lèvres, gloss et crayons", DescriptionEn = "Lipsticks, gloss and lip liners", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "Brush" },
            new() { Id = 4, Name = "Maquillage Yeux", NameEn = "Eye Makeup", Description = "Mascaras, fards à paupières et eye-liners", DescriptionEn = "Mascaras, eyeshadows and eyeliners", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "Visibility" },
            new() { Id = 5, Name = "Soins Visage", NameEn = "Face Care", Description = "Crèmes, sérums et nettoyants visage", DescriptionEn = "Face creams, serums and cleansers", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "FaceRetouchingNatural" },
            new() { Id = 6, Name = "Soins Corps", NameEn = "Body Care", Description = "Laits corporels, gommages et huiles", DescriptionEn = "Body lotions, scrubs and oils", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "Spa" },
            new() { Id = 7, Name = "Teint", NameEn = "Complexion", Description = "Fonds de teint, correcteurs et poudres", DescriptionEn = "Foundations, concealers and powders", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "Palette" },
            new() { Id = 8, Name = "Soins Cheveux", NameEn = "Hair Care", Description = "Shampoings, après-shampoings et masques", DescriptionEn = "Shampoos, conditioners and masks", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "ContentCut" },
            new() { Id = 9, Name = "Coffrets & Cadeaux", NameEn = "Gift Sets", Description = "Coffrets parfums et coffrets beauté", DescriptionEn = "Fragrance sets and beauty gift sets", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "CardGiftcard" },
            new() { Id = 10, Name = "Solaires", NameEn = "Sun Care", Description = "Protections solaires et autobronzants", DescriptionEn = "Sun protection and self-tanners", ProductCount = 10, SiteType = SiteType.Cosmetics, Icon = "WbSunny" }
        };
    }

    public static List<Product> GenerateProducts()
    {
        var products = new List<Product>
        {
            // Cat 1: Parfums Femme
            P(1, 1, "Chanel N°5 Eau de Parfum", "Chanel No.5 Eau de Parfum", "L'iconique parfum floral aldéhydé, symbole intemporel d'élégance.", "The iconic aldehyde floral fragrance, timeless symbol of elegance.", 135.00m, null, "Chanel", "CHA-N5EDP", 30, false, true, false, false, V(1, "50ml", "50ml", "50ml", 0m, 30), V(2, "100ml", "100ml", "100ml", 50m, 20)),
            P(2, 1, "Dior J'adore Eau de Parfum", "Dior J'adore Eau de Parfum", "Bouquet floral solaire avec ylang-ylang, rose et jasmin.", "Solar floral bouquet with ylang-ylang, rose and jasmine.", 129.00m, 115.00m, "Dior", "DIO-JADORE", 25, false, true, true, true, V(3, "50ml", "50ml", "50ml", 0m, 25), V(4, "100ml", "100ml", "100ml", 45m, 18)),
            P(3, 1, "Lancôme La Vie Est Belle", "Lancome La Vie Est Belle", "Parfum gourmand iris avec notes de praline et vanille.", "Gourmand iris fragrance with praline and vanilla notes.", 119.00m, null, "Lancôme", "LAN-LVEB", 35, true, true, false, false, V(5, "50ml", "50ml", "50ml", 0m, 35), V(6, "75ml", "75ml", "75ml", 30m, 22), V(7, "100ml", "100ml", "100ml", 50m, 15)),
            P(4, 1, "Yves Saint Laurent Libre", "Yves Saint Laurent Libre", "Eau de parfum florale fougère avec lavande française et fleur d'oranger.", "Floral fougère eau de parfum with French lavender and orange blossom.", 115.00m, 99.00m, "YSL", "YSL-LIBRE", 28, false, false, false, true, V(8, "30ml", "30ml", "30ml", -30m, 35), V(9, "50ml", "50ml", "50ml", 0m, 28), V(10, "90ml", "90ml", "90ml", 40m, 18)),
            P(5, 1, "Guerlain Shalimar", "Guerlain Shalimar", "Parfum oriental vanillé légendaire, créé en 1925.", "Legendary vanilla oriental fragrance, created in 1925.", 125.00m, null, "Guerlain", "GUE-SHAL", 20, false, false, false, false, V(11, "50ml", "50ml", "50ml", 0m, 20), V(12, "90ml", "90ml", "90ml", 45m, 12)),
            P(6, 1, "Chloé Eau de Parfum", "Chloe Eau de Parfum", "Parfum floral frais avec rose de mai et pivoine.", "Fresh floral fragrance with May rose and peony.", 99.00m, 85.00m, "Chloé", "CHL-EDP", 32, false, false, true, true, V(13, "30ml", "30ml", "30ml", -25m, 40), V(14, "50ml", "50ml", "50ml", 0m, 32), V(15, "75ml", "75ml", "75ml", 30m, 20)),
            P(7, 1, "Hermès Twilly d'Hermès", "Hermes Twilly d'Hermes", "Parfum épicé floral avec gingembre, tubéreuse et santal.", "Spicy floral fragrance with ginger, tuberose and sandalwood.", 109.00m, null, "Hermès", "HER-TWILLY", 18, true, false, false, false, V(16, "30ml", "30ml", "30ml", -25m, 25), V(17, "50ml", "50ml", "50ml", 0m, 18), V(18, "85ml", "85ml", "85ml", 40m, 10)),
            P(8, 1, "Versace Bright Crystal", "Versace Bright Crystal", "Eau de toilette fraîche et florale avec magnolia et musc.", "Fresh floral eau de toilette with magnolia and musk.", 79.00m, 65.00m, "Versace", "VER-BRIGHT", 40, false, false, false, true, V(19, "30ml", "30ml", "30ml", -20m, 50), V(20, "50ml", "50ml", "50ml", 0m, 40), V(21, "90ml", "90ml", "90ml", 30m, 25)),
            P(9, 1, "Mugler Angel Eau de Parfum", "Mugler Angel Eau de Parfum", "Parfum oriental gourmand avec praline, chocolat et patchouli.", "Gourmand oriental fragrance with praline, chocolate and patchouli.", 95.00m, null, "Mugler", "MUG-ANGEL", 22, false, true, false, false, V(22, "25ml", "25ml", "25ml", -20m, 30), V(23, "50ml", "50ml", "50ml", 0m, 22)),
            P(10, 1, "Prada Paradoxe", "Prada Paradoxe", "Eau de parfum ambrée florale avec notes de néroli et musc ambré.", "Amber floral eau de parfum with neroli and amber musk notes.", 105.00m, 89.00m, "Prada", "PRA-PARADOXE", 26, true, false, false, true, V(24, "30ml", "30ml", "30ml", -25m, 35), V(25, "50ml", "50ml", "50ml", 0m, 26), V(26, "90ml", "90ml", "90ml", 40m, 15)),

            // Cat 2: Parfums Homme
            P(11, 2, "Dior Sauvage Eau de Parfum", "Dior Sauvage Eau de Parfum", "Parfum boisé ambré frais avec ambroxan et poivre de Calabre.", "Fresh amber woody fragrance with ambroxan and Calabrian pepper.", 115.00m, null, "Dior", "DIO-SAUVAGE", 30, true, true, false, false, V(27, "60ml", "60ml", "60ml", 0m, 30), V(28, "100ml", "100ml", "100ml", 35m, 22), V(29, "200ml", "200ml", "200ml", 75m, 10)),
            P(12, 2, "Bleu de Chanel Eau de Parfum", "Bleu de Chanel Eau de Parfum", "Parfum boisé aromatique avec cèdre, santal et labdanum.", "Aromatic woody fragrance with cedar, sandalwood and labdanum.", 125.00m, 109.00m, "Chanel", "CHA-BLEU", 25, false, true, true, true, V(30, "50ml", "50ml", "50ml", 0m, 25), V(31, "100ml", "100ml", "100ml", 40m, 18), V(32, "150ml", "150ml", "150ml", 65m, 12)),
            P(13, 2, "Jean Paul Gaultier Le Mâle Elixir", "Jean Paul Gaultier Le Male Elixir", "Parfum oriental vanillé intense avec lavande et ambre.", "Intense vanilla oriental fragrance with lavender and amber.", 99.00m, null, "Jean Paul Gaultier", "JPG-MALE-ELIX", 20, false, false, false, false, V(33, "75ml", "75ml", "75ml", 0m, 20), V(34, "125ml", "125ml", "125ml", 30m, 14)),
            P(14, 2, "Armani Acqua di Giò Profondo", "Armani Acqua di Gio Profondo", "Eau de parfum aquatique avec notes marines et patchouli.", "Aquatic eau de parfum with marine notes and patchouli.", 105.00m, 89.00m, "Armani", "ARM-ADGP", 28, false, true, false, true, V(35, "40ml", "40ml", "40ml", -20m, 35), V(36, "75ml", "75ml", "75ml", 0m, 28), V(37, "125ml", "125ml", "125ml", 35m, 18)),
            P(15, 2, "Paco Rabanne 1 Million Elixir", "Paco Rabanne 1 Million Elixir", "Parfum intense cuir ambré avec notes fumées et vanille.", "Intense amber leather fragrance with smoky and vanilla notes.", 95.00m, null, "Paco Rabanne", "PAC-1MELIX", 22, true, false, false, false, V(38, "50ml", "50ml", "50ml", 0m, 22), V(39, "100ml", "100ml", "100ml", 35m, 15)),
            P(16, 2, "Hugo Boss Bottled Eau de Parfum", "Hugo Boss Bottled Eau de Parfum", "Parfum boisé élégant avec pomme, cannelle et bois de cèdre.", "Elegant woody fragrance with apple, cinnamon and cedarwood.", 85.00m, 72.00m, "Hugo Boss", "HUG-BOTTLED", 35, false, false, false, true, V(40, "50ml", "50ml", "50ml", 0m, 35), V(41, "100ml", "100ml", "100ml", 30m, 25), V(42, "200ml", "200ml", "200ml", 55m, 12)),
            P(17, 2, "Valentino Uomo Born in Roma", "Valentino Uomo Born in Roma", "Eau de toilette aromatique épicée avec genièvre et sauge.", "Spicy aromatic eau de toilette with juniper and sage.", 89.00m, null, "Valentino", "VAL-BIR", 24, false, false, false, false, V(43, "50ml", "50ml", "50ml", 0m, 24), V(44, "100ml", "100ml", "100ml", 30m, 16)),
            P(18, 2, "Versace Pour Homme", "Versace Pour Homme", "Eau de toilette fraîche méditerranéenne avec néroli, citron et ambre.", "Fresh Mediterranean eau de toilette with neroli, lemon and amber.", 69.00m, 55.00m, "Versace", "VER-PH", 40, false, false, true, true, V(45, "50ml", "50ml", "50ml", 0m, 40), V(46, "100ml", "100ml", "100ml", 25m, 30)),
            P(19, 2, "YSL Y Eau de Parfum", "YSL Y Eau de Parfum", "Parfum boisé frais avec pomme de Granny Smith et bois d'ambre.", "Fresh woody fragrance with Granny Smith apple and amberwood.", 99.00m, null, "YSL", "YSL-Y", 26, true, false, false, false, V(47, "60ml", "60ml", "60ml", 0m, 26), V(48, "100ml", "100ml", "100ml", 30m, 18)),
            P(20, 2, "Montblanc Explorer Ultra Blue", "Montblanc Explorer Ultra Blue", "Eau de parfum marine fraîche avec bergamote et bois flotté.", "Fresh marine eau de parfum with bergamot and driftwood.", 75.00m, 62.00m, "Montblanc", "MBL-EXUB", 32, false, false, false, true, V(49, "60ml", "60ml", "60ml", 0m, 32), V(50, "100ml", "100ml", "100ml", 20m, 22)),

            // Cat 3: Maquillage Lèvres
            P(21, 3, "MAC Lipstick Matte Ruby Woo", "MAC Lipstick Matte Ruby Woo", "Rouge à lèvres mat iconique, rouge vif rétro.", "Iconic matte lipstick, retro vivid red.", 23.50m, null, "MAC", "MAC-RW", 60, false, true, false, false, V(51, "Ruby Woo", "Ruby Woo", "Ruby Woo", 0m, 60), V(52, "Lady Danger", "Lady Danger", "Lady Danger", 0m, 45)),
            P(22, 3, "Dior Addict Lip Maximizer", "Dior Addict Lip Maximizer", "Gloss repulpant avec acide hyaluronique pour lèvres pulpeuses.", "Plumping gloss with hyaluronic acid for fuller lips.", 38.00m, 33.00m, "Dior", "DIO-ADLM", 40, true, true, false, true, V(53, "001 Rose Pâle", "001 Pale Pink", "001", 0m, 40), V(54, "012 Rosewood", "012 Rosewood", "012", 0m, 35)),
            P(23, 3, "Charlotte Tilbury Pillow Talk", "Charlotte Tilbury Pillow Talk", "Rouge à lèvres nude-rose best-seller avec fini velouté.", "Best-selling nude-pink lipstick with velvety finish.", 35.00m, null, "Charlotte Tilbury", "CT-PT", 45, false, true, false, false, V(55, "Original", "Original", "Original", 0m, 45), V(56, "Medium", "Medium", "Medium", 0m, 35)),
            P(24, 3, "YSL Rouge Pur Couture", "YSL Rouge Pur Couture", "Rouge à lèvres satiné avec soin lèvres enrichi en huile de grenade.", "Satin lipstick with lip care enriched with pomegranate oil.", 40.00m, 35.00m, "YSL", "YSL-RPC", 35, false, false, true, true, V(57, "N°1 Le Rouge", "No.1 Le Rouge", "N1", 0m, 35), V(58, "N°13 Le Orange", "No.13 Le Orange", "N13", 0m, 28)),
            P(25, 3, "Fenty Beauty Gloss Bomb", "Fenty Beauty Gloss Bomb", "Gloss universel brillance explosive avec vitamine E.", "Universal explosive shine gloss with vitamin E.", 22.00m, null, "Fenty Beauty", "FEN-GB", 50, true, false, false, false, V(59, "Fenty Glow", "Fenty Glow", "Glow", 0m, 50), V(60, "Fu$$y", "Fu$$y", "Fussy", 0m, 40)),
            P(26, 3, "NARS Powermatte Lipstick", "NARS Powermatte Lipstick", "Rouge à lèvres longue tenue mat intense, 12h de tenue.", "Intense matte long-lasting lipstick, 12h wear.", 30.00m, 25.00m, "NARS", "NAR-PML", 38, false, false, false, true, V(61, "Dragon Girl", "Dragon Girl", "Dragon", 0m, 38), V(62, "American Woman", "American Woman", "American", 0m, 30)),
            P(27, 3, "L'Oréal Paris Color Riche Satin", "L'Oreal Paris Color Riche Satin", "Rouge à lèvres satiné enrichi en huile d'argan, 4h de confort.", "Satin lipstick enriched with argan oil, 4h comfort.", 12.90m, 9.90m, "L'Oréal Paris", "LOR-CRS", 80, false, false, true, true, V(63, "377 Perfect Red", "377 Perfect Red", "377", 0m, 80), V(64, "235 Nude", "235 Nude", "235", 0m, 70)),
            P(28, 3, "Rare Beauty Soft Pinch Liquid Blush", "Rare Beauty Soft Pinch Liquid Blush", "Blush liquide ultra-pigmenté avec fini naturel aérien.", "Ultra-pigmented liquid blush with airy natural finish.", 24.00m, null, "Rare Beauty", "RAR-SPLB", 42, true, true, false, false, V(65, "Joy", "Joy", "Joy", 0m, 42), V(66, "Grateful", "Grateful", "Grateful", 0m, 35)),
            P(29, 3, "Givenchy Le Rouge Deep Velvet", "Givenchy Le Rouge Deep Velvet", "Rouge à lèvres poudré mat avec pigment velours.", "Powdery matte lipstick with velvet pigment.", 42.00m, null, "Givenchy", "GIV-LRDV", 25, false, false, false, false, V(67, "N°37 Rouge Grainé", "No.37 Rouge Graine", "N37", 0m, 25)),
            P(30, 3, "Too Faced Lip Injection Extreme", "Too Faced Lip Injection Extreme", "Gloss repulpant effet piment avec résultats immédiats.", "Plumping gloss with chili effect and immediate results.", 29.00m, 24.00m, "Too Faced", "TF-LIE", 36, false, false, false, true, V(68, "Rose", "Pink", "Rose", 0m, 36), V(69, "Corail", "Coral", "Corail", 0m, 28)),

            // Cat 4-10: remaining products (abbreviated for space but still realistic)
            // Cat 4: Maquillage Yeux
            P(31, 4, "Lancôme Hypnôse Mascara", "Lancome Hypnose Mascara", "Mascara volume sur mesure avec brosse S brevetée.", "Custom volume mascara with patented S-shaped brush.", 32.00m, 27.00m, "Lancôme", "LAN-HYP", 45, true, true, false, true, V(70, "Noir", "Black", "Noir", 0m, 45)),
            P(32, 4, "Maybelline Lash Sensational Sky High", "Maybelline Lash Sensational Sky High", "Mascara allongeant avec brosse flexible et formule infusée de bambou.", "Lengthening mascara with flexible brush and bamboo-infused formula.", 12.90m, 9.90m, "Maybelline", "MAY-LSSH", 70, false, true, true, true, V(71, "Noir", "Black", "Noir", 0m, 70)),
            P(33, 4, "Urban Decay Naked3 Palette", "Urban Decay Naked3 Palette", "Palette 12 fards à paupières rosés avec finis mat, satiné et shimmer.", "12-shade rose-hued eyeshadow palette with matte, satin and shimmer finishes.", 52.00m, null, "Urban Decay", "UD-NK3", 25, false, false, false, false, V(72, "Standard", "Standard", "Standard", 0m, 25)),
            P(34, 4, "Chanel Le Volume de Chanel", "Chanel Le Volume de Chanel", "Mascara volume intense avec brosse sculptante brevetée.", "Intense volume mascara with patented sculpting brush.", 35.00m, null, "Chanel", "CHA-LVC", 30, false, true, false, false, V(73, "10 Noir", "10 Noir", "Noir", 0m, 30)),
            P(35, 4, "Charlotte Tilbury Eyes to Mesmerise", "Charlotte Tilbury Eyes to Mesmerise", "Fard à paupières crème longue tenue avec fini soyeux.", "Long-lasting cream eyeshadow with silky finish.", 29.00m, 24.00m, "Charlotte Tilbury", "CT-ETM", 35, false, false, false, true, V(74, "Champagne", "Champagne", "Champagne", 0m, 35), V(75, "Bronze", "Bronze", "Bronze", 0m, 28)),
            P(36, 4, "Benefit Roller Lash Mascara", "Benefit Roller Lash Mascara", "Mascara recourbant avec brosse Hook'n'Roll pour cils recourbés.", "Curling mascara with Hook'n'Roll brush for curled lashes.", 28.00m, null, "Benefit", "BEN-RL", 40, true, false, false, false, V(76, "Noir", "Black", "Noir", 0m, 40)),
            P(37, 4, "Too Faced Better Than Sex Mascara", "Too Faced Better Than Sex Mascara", "Mascara volume collagène avec brosse sablier.", "Collagen volume mascara with hourglass-shaped brush.", 26.00m, 22.00m, "Too Faced", "TF-BTS", 50, false, false, true, true, V(77, "Noir", "Black", "Noir", 0m, 50)),
            P(38, 4, "Dior Diorshow Iconic Overcurl", "Dior Diorshow Iconic Overcurl", "Mascara courbe spectaculaire avec formule enrichie en soins.", "Spectacular curl mascara with care-enriched formula.", 36.00m, null, "Dior", "DIO-DIOC", 28, false, false, false, false, V(78, "090 Noir", "090 Black", "Noir", 0m, 28)),
            P(39, 4, "NYX Epic Ink Liner", "NYX Epic Ink Liner", "Eye-liner feutre waterproof ultra-précis et longue tenue.", "Ultra-precise waterproof felt-tip eyeliner, long-lasting.", 9.90m, 7.90m, "NYX", "NYX-EIL", 80, false, false, false, true, V(79, "Noir", "Black", "Noir", 0m, 80)),
            P(40, 4, "Huda Beauty Rose Gold Palette", "Huda Beauty Rose Gold Palette", "Palette 18 fards or rose avec textures mattes, shimmer et pailletées.", "18-shade rose gold palette with matte, shimmer and glitter textures.", 65.00m, null, "Huda Beauty", "HUD-RGP", 18, false, false, false, false, V(80, "Standard", "Standard", "Standard", 0m, 18)),

            // Cat 5: Soins Visage
            P(41, 5, "La Roche-Posay Effaclar Duo+", "La Roche-Posay Effaclar Duo+", "Soin anti-imperfections avec niacinamide et acide salicylique.", "Anti-blemish care with niacinamide and salicylic acid.", 17.90m, 14.90m, "La Roche-Posay", "LRP-EFF", 60, false, true, true, true, V(81, "40ml", "40ml", "40ml", 0m, 60)),
            P(42, 5, "CeraVe Crème Hydratante Visage", "CeraVe Moisturizing Face Cream", "Crème hydratante avec 3 céramides essentiels et acide hyaluronique.", "Moisturizing cream with 3 essential ceramides and hyaluronic acid.", 14.90m, null, "CeraVe", "CER-CHV", 80, false, true, false, false, V(82, "52ml", "52ml", "52ml", 0m, 80)),
            P(43, 5, "Estée Lauder Advanced Night Repair", "Estee Lauder Advanced Night Repair", "Sérum réparateur nuit avec technologie Chronolux Power Signal.", "Night repair serum with Chronolux Power Signal technology.", 89.00m, 75.00m, "Estée Lauder", "EL-ANR", 25, true, true, false, true, V(83, "30ml", "30ml", "30ml", 0m, 25), V(84, "50ml", "50ml", "50ml", 40m, 15)),
            P(44, 5, "The Ordinary Niacinamide 10% + Zinc 1%", "The Ordinary Niacinamide 10% + Zinc 1%", "Sérum anti-pores et anti-imperfections haute concentration.", "High-concentration anti-pore and anti-blemish serum.", 6.80m, null, "The Ordinary", "TO-NIAZ", 100, false, false, false, false, V(85, "30ml", "30ml", "30ml", 0m, 100), V(86, "60ml", "60ml", "60ml", 4m, 50)),
            P(45, 5, "Clinique Moisture Surge 100H", "Clinique Moisture Surge 100H", "Gel-crème hydratant 100 heures avec technologie Auto-Replenishing.", "100-hour hydrating gel-cream with Auto-Replenishing technology.", 42.00m, 35.00m, "Clinique", "CLI-MS100", 35, false, false, false, true, V(87, "30ml", "30ml", "30ml", -10m, 45), V(88, "50ml", "50ml", "50ml", 0m, 35)),
            P(46, 5, "Vichy Minéral 89 Booster", "Vichy Mineral 89 Booster", "Sérum fortifiant avec 89% d'eau volcanique de Vichy et acide hyaluronique.", "Fortifying serum with 89% Vichy volcanic water and hyaluronic acid.", 22.90m, 18.90m, "Vichy", "VIC-M89", 55, false, false, true, true, V(89, "30ml", "30ml", "30ml", 0m, 55), V(90, "50ml", "50ml", "50ml", 8m, 35)),
            P(47, 5, "Kiehl's Ultra Facial Cream", "Kiehl's Ultra Facial Cream", "Crème hydratante 24h légère avec squalane glaciaire.", "24h lightweight moisturizing cream with glacial glycoprotein.", 32.00m, null, "Kiehl's", "KIE-UFC", 30, true, false, false, false, V(91, "50ml", "50ml", "50ml", 0m, 30), V(92, "125ml", "125ml", "125ml", 20m, 18)),
            P(48, 5, "Bioderma Sensibio H2O", "Bioderma Sensibio H2O", "Eau micellaire peaux sensibles, nettoyant doux sans rinçage.", "Micellar water for sensitive skin, gentle no-rinse cleanser.", 12.90m, 9.90m, "Bioderma", "BIO-SH2O", 90, false, false, true, true, V(93, "250ml", "250ml", "250ml", 0m, 90), V(94, "500ml", "500ml", "500ml", 5m, 60)),
            P(49, 5, "Drunk Elephant Protini Polypeptide", "Drunk Elephant Protini Polypeptide", "Crème protéinée aux peptides pour peau rebondie et ferme.", "Protein-rich peptide cream for bouncy, firm skin.", 68.00m, null, "Drunk Elephant", "DE-PPC", 18, false, false, false, false, V(95, "50ml", "50ml", "50ml", 0m, 18)),
            P(50, 5, "Caudalie Vinoperfect Sérum", "Caudalie Vinoperfect Serum", "Sérum éclat anti-taches avec Viniférine, 62x plus efficace que la vitamine C.", "Radiance anti-dark spot serum with Viniferine, 62x more effective than vitamin C.", 39.90m, 33.90m, "Caudalie", "CAU-VPS", 28, true, false, false, true, V(96, "30ml", "30ml", "30ml", 0m, 28)),

            // Cat 6: Soins Corps
            P(51, 6, "Nivea Lait Corps Nourrissant", "Nivea Nourishing Body Lotion", "Lait corporel nourrissant pour peaux sèches avec beurre de karité.", "Nourishing body lotion for dry skin with shea butter.", 6.90m, 4.90m, "Nivea", "NIV-LCN", 100, false, true, true, true, V(97, "400ml", "400ml", "400ml", 0m, 100)),
            P(52, 6, "Nuxe Huile Prodigieuse", "Nuxe Huile Prodigieuse", "Huile sèche multi-usage visage-corps-cheveux avec 7 huiles précieuses.", "Multi-purpose dry oil for face-body-hair with 7 precious oils.", 29.90m, null, "Nuxe", "NUX-HP", 45, true, true, false, false, V(98, "50ml", "50ml", "50ml", -10m, 60), V(99, "100ml", "100ml", "100ml", 0m, 45)),
            P(53, 6, "Sol de Janeiro Brazilian Bum Bum Cream", "Sol de Janeiro Brazilian Bum Bum Cream", "Crème corps raffermissante au cupuaçu et guaraná avec scent signature.", "Firming body cream with cupuaçu and guaraná with signature scent.", 48.00m, 40.00m, "Sol de Janeiro", "SDJ-BBC", 30, false, false, false, true, V(100, "240ml", "240ml", "240ml", 0m, 30)),
            P(54, 6, "L'Occitane Beurre de Karité", "L'Occitane Shea Butter", "Beurre de karité pur à 100% pour nourrir intensément la peau.", "100% pure shea butter for intense skin nourishment.", 38.00m, null, "L'Occitane", "LOC-BK", 25, false, false, false, false, V(101, "150ml", "150ml", "150ml", 0m, 25)),
            P(55, 6, "Dove Gel Douche Soin", "Dove Care Body Wash", "Gel douche hydratant avec 1/4 de crème hydratante.", "Moisturizing body wash with 1/4 moisturizing cream.", 4.50m, 3.50m, "Dove", "DOV-GDS", 120, false, false, true, true, V(102, "250ml", "250ml", "250ml", 0m, 120), V(103, "500ml", "500ml", "500ml", 2m, 80)),
            P(56, 6, "Rituals Sakura Body Cream", "Rituals Sakura Body Cream", "Crème corps fleur de cerisier avec lait de riz pour peau soyeuse.", "Cherry blossom body cream with rice milk for silky skin.", 19.90m, null, "Rituals", "RIT-SBC", 35, false, false, false, false, V(104, "220ml", "220ml", "220ml", 0m, 35)),
            P(57, 6, "Biotherm Lait Corporel", "Biotherm Body Milk", "Lait corporel anti-dessèchement avec extrait d'algue thermale.", "Anti-dryness body milk with thermal algae extract.", 25.90m, 21.90m, "Biotherm", "BIO-LC", 40, false, true, false, true, V(105, "200ml", "200ml", "200ml", 0m, 40), V(106, "400ml", "400ml", "400ml", 12m, 25)),
            P(58, 6, "The Body Shop Moringa Body Butter", "The Body Shop Moringa Body Butter", "Beurre corporel au moringa du commerce équitable pour peau nourrie.", "Moringa body butter from fair trade for nourished skin.", 22.00m, null, "The Body Shop", "TBS-MBB", 30, false, false, false, false, V(107, "200ml", "200ml", "200ml", 0m, 30)),
            P(59, 6, "Mixa Lait Corps Peaux Sèches", "Mixa Body Lotion Dry Skin", "Lait corps nutritif intensif avec panthénol et huile d'onagre.", "Intensive nourishing body lotion with panthenol and evening primrose oil.", 5.90m, 4.50m, "Mixa", "MIX-LCPS", 90, false, false, false, true, V(108, "250ml", "250ml", "250ml", 0m, 90), V(109, "400ml", "400ml", "400ml", 2m, 60)),
            P(60, 6, "Roger & Gallet Gel Douche Feuille de Figuier", "Roger & Gallet Fig Leaf Shower Gel", "Gel douche frais et vivifiant à la feuille de figuier.", "Fresh and invigorating fig leaf shower gel.", 9.90m, null, "Roger & Gallet", "RG-GDFF", 50, true, false, false, false, V(110, "200ml", "200ml", "200ml", 0m, 50)),

            // Cat 7: Teint
            P(61, 7, "Fenty Beauty Pro Filt'r Soft Matte", "Fenty Beauty Pro Filt'r Soft Matte", "Fond de teint longue tenue 50 teintes avec fini mat naturel.", "Long-wear 50-shade foundation with natural matte finish.", 39.00m, 33.00m, "Fenty Beauty", "FEN-PF", 35, true, true, true, true, V(111, "130 Clair", "130 Light", "130", 0m, 35), V(112, "240 Moyen", "240 Medium", "240", 0m, 30), V(113, "385 Foncé", "385 Dark", "385", 0m, 25)),
            P(62, 7, "NARS Sheer Glow Foundation", "NARS Sheer Glow Foundation", "Fond de teint lumineux avec fini satiné et formule enrichie.", "Luminous foundation with satin finish and enriched formula.", 47.00m, null, "NARS", "NAR-SGF", 25, false, true, false, false, V(114, "Deauville", "Deauville", "Deauville", 0m, 25), V(115, "Barcelona", "Barcelona", "Barcelona", 0m, 20)),
            P(63, 7, "Maybelline Fit Me Matte+Poreless", "Maybelline Fit Me Matte+Poreless", "Fond de teint matifiant anti-pores à prix accessible.", "Mattifying anti-pore foundation at an accessible price.", 9.90m, 7.90m, "Maybelline", "MAY-FMMP", 80, false, false, true, true, V(116, "110 Porcelaine", "110 Porcelain", "110", 0m, 80), V(117, "220 Natural Beige", "220 Natural Beige", "220", 0m, 70), V(118, "330 Toffee", "330 Toffee", "330", 0m, 50)),
            P(64, 7, "Charlotte Tilbury Airbrush Flawless", "Charlotte Tilbury Airbrush Flawless", "Fond de teint full cover longue tenue avec fini poudreux.", "Full coverage long-wearing foundation with powdery finish.", 44.00m, null, "Charlotte Tilbury", "CT-AF", 22, false, false, false, false, V(119, "3 Neutral", "3 Neutral", "3N", 0m, 22), V(120, "6 Warm", "6 Warm", "6W", 0m, 18)),
            P(65, 7, "L'Oréal True Match Fond de Teint", "L'Oreal True Match Foundation", "Fond de teint soin avec acide hyaluronique et 98% d'ingrédients naturels.", "Skincare foundation with hyaluronic acid and 98% natural ingredients.", 13.90m, 10.90m, "L'Oréal Paris", "LOR-TM", 75, false, true, false, true, V(121, "2.R Vanille Rosé", "2.R Vanilla Rose", "2R", 0m, 75), V(122, "5.N Sable", "5.N Sand", "5N", 0m, 60)),
            P(66, 7, "MAC Studio Fix Fluid SPF15", "MAC Studio Fix Fluid SPF15", "Fond de teint fluide mat naturel avec SPF15 et 67 teintes.", "Natural matte fluid foundation with SPF15 and 67 shades.", 38.00m, null, "MAC", "MAC-SFF", 30, false, false, false, false, V(123, "NC15", "NC15", "NC15", 0m, 30), V(124, "NC30", "NC30", "NC30", 0m, 25), V(125, "NC42", "NC42", "NC42", 0m, 20)),
            P(67, 7, "Dior Forever Foundation", "Dior Forever Foundation", "Fond de teint haute perfection 24h avec soin floral et transfert zéro.", "24h high-perfection foundation with floral skincare and zero transfer.", 52.00m, 45.00m, "Dior", "DIO-DFF", 20, true, false, false, true, V(126, "1N Neutre", "1N Neutral", "1N", 0m, 20), V(127, "3W Warm", "3W Warm", "3W", 0m, 16)),
            P(68, 7, "Tarte Shape Tape Concealer", "Tarte Shape Tape Concealer", "Correcteur full cover best-seller avec applicateur sculptant.", "Best-selling full coverage concealer with sculpting applicator.", 29.00m, null, "Tarte", "TAR-STC", 40, false, true, false, false, V(128, "Fair Light", "Fair Light", "FairLight", 0m, 40), V(129, "Medium", "Medium", "Medium", 0m, 35)),
            P(69, 7, "Hourglass Veil Translucent Powder", "Hourglass Veil Translucent Powder", "Poudre fixatrice translucide avec fini flouteur et ultra-fine.", "Translucent setting powder with blurring finish and ultra-fine texture.", 48.00m, 40.00m, "Hourglass", "HG-VTP", 22, false, false, false, true, V(130, "Translucent", "Translucent", "Translucent", 0m, 22)),
            P(70, 7, "NYX HD Finishing Powder", "NYX HD Finishing Powder", "Poudre libre minérale HD pour fini photographique impeccable.", "HD mineral loose powder for flawless photographic finish.", 9.90m, null, "NYX", "NYX-HDFP", 65, false, false, false, false, V(131, "Translucide", "Translucent", "Translucide", 0m, 65), V(132, "Banana", "Banana", "Banana", 0m, 45)),

            // Cat 8: Soins Cheveux
            P(71, 8, "Kérastase Elixir Ultime L'Huile Originale", "Kerastase Elixir Ultime L'Huile Originale", "Huile capillaire sublimante aux 4 huiles pour tous types de cheveux.", "Sublime hair oil with 4 oils for all hair types.", 42.00m, 35.00m, "Kérastase", "KER-EU", 30, true, true, false, true, V(133, "100ml", "100ml", "100ml", 0m, 30)),
            P(72, 8, "Olaplex No.3 Hair Perfector", "Olaplex No.3 Hair Perfector", "Soin réparateur profond qui reconstruit les liaisons capillaires.", "Deep repair treatment that rebuilds hair bonds.", 28.00m, null, "Olaplex", "OLA-N3", 40, false, true, false, false, V(134, "100ml", "100ml", "100ml", 0m, 40)),
            P(73, 8, "Garnier Fructis Hair Food Banane", "Garnier Fructis Hair Food Banana", "Masque nourrissant 3-en-1 pour cheveux secs avec extrait de banane.", "3-in-1 nourishing mask for dry hair with banana extract.", 5.90m, 4.50m, "Garnier", "GAR-HFB", 90, false, false, true, true, V(135, "390ml", "390ml", "390ml", 0m, 90)),
            P(74, 8, "Moroccanoil Original Treatment", "Moroccanoil Original Treatment", "Huile d'argan traitante pour cheveux brillants et soyeux.", "Argan oil treatment for shiny and silky hair.", 35.90m, null, "Moroccanoil", "MOR-OT", 25, false, true, false, false, V(136, "25ml", "25ml", "25ml", -15m, 35), V(137, "100ml", "100ml", "100ml", 0m, 25)),
            P(75, 8, "L'Oréal Professionnel Série Expert", "L'Oreal Professionnel Serie Expert", "Shampoing Golden Repair pour cheveux abîmés.", "Golden Repair shampoo for damaged hair.", 16.90m, 13.90m, "L'Oréal Professionnel", "LORP-SE", 50, false, false, false, true, V(138, "300ml", "300ml", "300ml", 0m, 50), V(139, "500ml", "500ml", "500ml", 6m, 30)),
            P(76, 8, "René Furterer Huile 5 Sens", "Rene Furterer 5 Sens Oil", "Huile sublimatrice sèche pour corps et cheveux aux 5 huiles végétales.", "Beautifying dry oil for body and hair with 5 plant oils.", 22.90m, null, "René Furterer", "RF-H5S", 35, true, false, false, false, V(140, "100ml", "100ml", "100ml", 0m, 35)),
            P(77, 8, "Head & Shoulders Classic Clean", "Head & Shoulders Classic Clean", "Shampooing antipelliculaire classique au zinc pyrithione.", "Classic anti-dandruff shampoo with zinc pyrithione.", 4.90m, 3.50m, "Head & Shoulders", "HS-CC", 100, false, false, true, true, V(141, "250ml", "250ml", "250ml", 0m, 100), V(142, "500ml", "500ml", "500ml", 3m, 70)),
            P(78, 8, "Kérastase Discipline Bain Fluidealiste", "Kerastase Discipline Bain Fluidealiste", "Shampoing lissant antifrisottis à la morpho-kératine.", "Anti-frizz smoothing shampoo with Morpho-Keratin.", 29.00m, null, "Kérastase", "KER-DBF", 28, false, false, false, false, V(143, "250ml", "250ml", "250ml", 0m, 28)),
            P(79, 8, "Christophe Robin Masque Prickly Pear", "Christophe Robin Prickly Pear Mask", "Masque capillaire régénérant à l'huile de figue de barbarie.", "Regenerating hair mask with prickly pear seed oil.", 45.00m, 38.00m, "Christophe Robin", "CR-MPP", 20, false, false, false, true, V(144, "250ml", "250ml", "250ml", 0m, 20)),
            P(80, 8, "Aussie 3 Minute Miracle Moist", "Aussie 3 Minute Miracle Moist", "Après-shampoing intensif 3 minutes pour cheveux déshydratés.", "3-minute intensive conditioner for dehydrated hair.", 5.90m, null, "Aussie", "AUS-3MM", 75, false, false, false, false, V(145, "250ml", "250ml", "250ml", 0m, 75)),

            // Cat 9: Coffrets & Cadeaux
            P(81, 9, "Dior Coffret J'adore", "Dior J'adore Gift Set", "Coffret EDP 50ml + lait corps 75ml dans écrin Dior.", "EDP 50ml + body milk 75ml gift set in Dior case.", 105.00m, 89.00m, "Dior", "DIO-CJAD", 20, true, true, true, true, V(146, "Standard", "Standard", "Standard", 0m, 20)),
            P(82, 9, "Chanel Coffret Coco Mademoiselle", "Chanel Coco Mademoiselle Gift Set", "Coffret EDP 50ml + crème corps 150ml en édition limitée.", "EDP 50ml + body cream 150ml limited edition gift set.", 125.00m, null, "Chanel", "CHA-CCM", 15, false, true, false, false, V(147, "Standard", "Standard", "Standard", 0m, 15)),
            P(83, 9, "YSL Black Opium Coffret", "YSL Black Opium Gift Set", "Coffret EDP 30ml + lait corps 50ml + trousse beauté.", "EDP 30ml + body lotion 50ml + beauty pouch gift set.", 79.00m, 69.00m, "YSL", "YSL-CBOP", 25, false, false, false, true, V(148, "Standard", "Standard", "Standard", 0m, 25)),
            P(84, 9, "Lancôme Coffret La Vie Est Belle", "Lancome La Vie Est Belle Gift Set", "Coffret EDP 50ml + lait 50ml + mascara Hypnôse mini.", "EDP 50ml + body milk 50ml + mini Hypnose mascara gift set.", 89.00m, null, "Lancôme", "LAN-CLVEB", 18, true, false, false, false, V(149, "Standard", "Standard", "Standard", 0m, 18)),
            P(85, 9, "Sephora Calendrier de l'Avent Beauté", "Sephora Beauty Advent Calendar", "Calendrier de l'Avent 24 surprises beauté de grandes marques.", "24-day beauty advent calendar with premium brand surprises.", 79.99m, 59.99m, "Sephora", "SEP-CAB", 30, false, false, true, true, V(150, "Standard", "Standard", "Standard", 0m, 30)),
            P(86, 9, "Guerlain Coffret Aqua Allegoria", "Guerlain Aqua Allegoria Gift Set", "Coffret découverte 5 miniatures Aqua Allegoria.", "Discovery set of 5 Aqua Allegoria miniatures.", 55.00m, null, "Guerlain", "GUE-CAA", 22, false, false, false, false, V(151, "Standard", "Standard", "Standard", 0m, 22)),
            P(87, 9, "Armani Coffret Si Passione", "Armani Si Passione Gift Set", "Coffret EDP 50ml + gel douche 75ml + lait corps 75ml.", "EDP 50ml + shower gel 75ml + body lotion 75ml gift set.", 95.00m, 82.00m, "Armani", "ARM-CSP", 16, false, true, false, true, V(152, "Standard", "Standard", "Standard", 0m, 16)),
            P(88, 9, "L'Occitane Coffret Mains", "L'Occitane Hand Cream Gift Set", "Coffret 6 crèmes mains 30ml aux senteurs provençales.", "6-piece 30ml hand cream gift set with Provençal scents.", 35.00m, null, "L'Occitane", "LOC-CM", 35, false, false, false, false, V(153, "Standard", "Standard", "Standard", 0m, 35)),
            P(89, 9, "Paco Rabanne Coffret 1 Million", "Paco Rabanne 1 Million Gift Set", "Coffret EDT 100ml + déodorant 150ml + voyage 10ml.", "EDT 100ml + deodorant 150ml + travel spray 10ml gift set.", 89.00m, 75.00m, "Paco Rabanne", "PAC-C1M", 20, true, false, false, true, V(154, "Standard", "Standard", "Standard", 0m, 20)),
            P(90, 9, "Rituals Coffret The Ritual of Sakura", "Rituals The Ritual of Sakura Gift Set", "Coffret 4 pièces fleur de cerisier : gel douche, crème, gommage, bougie.", "4-piece cherry blossom set: shower gel, cream, scrub, candle.", 29.90m, null, "Rituals", "RIT-CRS", 28, false, false, false, false, V(155, "Standard", "Standard", "Standard", 0m, 28)),

            // Cat 10: Solaires
            P(91, 10, "La Roche-Posay Anthelios UVMune 400 SPF50+", "La Roche-Posay Anthelios UVMune 400 SPF50+", "Crème solaire visage très haute protection avec Mexoryl 400.", "Very high protection face sunscreen with Mexoryl 400.", 18.90m, 15.90m, "La Roche-Posay", "LRP-ANT", 50, true, true, true, true, V(156, "50ml", "50ml", "50ml", 0m, 50)),
            P(92, 10, "Avène Solaire Fluide SPF50+", "Avene Sun Fluid SPF50+", "Fluide solaire ultra-léger très haute protection sans parfum.", "Ultra-light very high protection sun fluid, fragrance-free.", 16.90m, null, "Avène", "AVE-SFSPF50", 45, false, true, false, false, V(157, "50ml", "50ml", "50ml", 0m, 45)),
            P(93, 10, "Bioderma Photoderm MAX SPF50+", "Bioderma Photoderm MAX SPF50+", "Crème solaire très haute protection UVA/UVB avec texture invisible.", "Very high UVA/UVB protection sunscreen with invisible texture.", 15.90m, 12.90m, "Bioderma", "BIO-PMAX", 55, false, false, false, true, V(158, "40ml", "40ml", "40ml", 0m, 55)),
            P(94, 10, "Nuxe Sun Huile Bronzante SPF30", "Nuxe Sun Tanning Oil SPF30", "Huile bronzante haute protection visage et corps.", "High protection tanning oil for face and body.", 22.90m, null, "Nuxe", "NUX-SHB", 30, false, false, false, false, V(159, "150ml", "150ml", "150ml", 0m, 30)),
            P(95, 10, "Garnier Ambre Solaire Sensitive Expert+ SPF50+", "Garnier Ambre Solaire Sensitive Expert+ SPF50+", "Brume sèche protectrice SPF50+ peaux sensibles.", "Protective dry mist SPF50+ for sensitive skin.", 12.90m, 9.90m, "Garnier", "GAR-ASSE", 65, false, false, true, true, V(160, "200ml", "200ml", "200ml", 0m, 65)),
            P(96, 10, "Vichy Capital Soleil SPF50", "Vichy Capital Soleil SPF50", "Lait solaire multi-protection corps SPF50 avec eau volcanique.", "Multi-protection body sun milk SPF50 with volcanic water.", 17.90m, null, "Vichy", "VIC-CSSPF50", 40, true, false, false, false, V(161, "300ml", "300ml", "300ml", 0m, 40)),
            P(97, 10, "Lancaster Sun Beauty Satin Dry Oil SPF30", "Lancaster Sun Beauty Satin Dry Oil SPF30", "Huile sèche satinée bronzage sublime avec Full Light Technology.", "Sublime tan satin dry oil with Full Light Technology.", 32.00m, 27.00m, "Lancaster", "LAN-SBSDO", 22, false, false, false, true, V(162, "150ml", "150ml", "150ml", 0m, 22)),
            P(98, 10, "Hawaiian Tropic Silk Hydration SPF30", "Hawaiian Tropic Silk Hydration SPF30", "Lotion solaire ultra-hydratante avec rubans de soie.", "Ultra-moisturizing sun lotion with silk hydration ribbons.", 10.90m, null, "Hawaiian Tropic", "HT-SHSPF30", 50, false, false, false, false, V(163, "180ml", "180ml", "180ml", 0m, 50)),
            P(99, 10, "St. Tropez Self Tan Classic Bronzing Mousse", "St. Tropez Self Tan Classic Bronzing Mousse", "Mousse autobronzante pour un teint doré naturel en 4-8h.", "Self-tanning mousse for a natural golden tan in 4-8h.", 32.00m, 27.00m, "St. Tropez", "STT-STCBM", 25, false, true, false, true, V(164, "240ml", "240ml", "240ml", 0m, 25)),
            P(100, 10, "Institut Esthederm Bronz Repair Sunkissed SPF15", "Institut Esthederm Bronz Repair Sunkissed SPF15", "Crème bronz repair teintée pour peau protégée et résistante au soleil.", "Tinted bronz repair cream for protected and sun-resistant skin.", 42.00m, null, "Institut Esthederm", "EST-BRSPF15", 18, false, false, false, false, V(165, "50ml", "50ml", "50ml", 0m, 18)),
        };

        foreach (var p in products)
        {
            p.SiteType = SiteType.Cosmetics;
            p.RelatedProductIds = DataSeeder.GetRelatedIds(p.Id, products.Count);
            p.Tags = GenerateTags(p);
        }

        return products;
    }

    private static Product P(int id, int catId, string name, string nameEn, string desc, string descEn,
        decimal price, decimal? promo, string brand, string sku, int stock,
        bool isNew, bool isBestSeller, bool isFeatured, bool isPromo,
        params ProductVariant[] variants)
    {
        return new Product
        {
            Id = id, CategoryId = catId, Name = name, NameEn = nameEn,
            Description = desc, DescriptionEn = descEn, Price = price, PromoPrice = promo,
            Brand = brand, Sku = sku, Stock = stock,
            IsNew = isNew, IsBestSeller = isBestSeller, IsFeatured = isFeatured, IsPromo = isPromo,
            Variants = variants.ToList(),
            CreatedAt = DataSeeder.RandomRecentDate(),
            SiteType = SiteType.Cosmetics
        };
    }

    private static ProductVariant V(int id, string name, string nameEn, string value, decimal adj, int stock)
        => new() { Id = id, Name = name, NameEn = nameEn, Value = value, PriceAdjustment = adj, Stock = stock };

    private static List<string> GenerateTags(Product p)
    {
        var tags = new List<string> { p.Brand };
        if (p.IsNew) tags.Add("Nouveauté");
        if (p.IsPromo) tags.Add("Promo");
        if (p.IsBestSeller) tags.Add("Best-seller");
        return tags;
    }
}
