namespace Zava.Api.Services;

using Zava.Api.Models;

public static class ElectricalSeeder
{
    public static List<Category> GenerateCategories()
    {
        return new List<Category>
        {
            new() { Id = 1, Name = "Câbles & Fils", NameEn = "Cables & Wires", Description = "Câbles électriques, fils et gaines", DescriptionEn = "Electrical cables, wires and conduits", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "Cable" },
            new() { Id = 2, Name = "Disjoncteurs & Protection", NameEn = "Circuit Breakers & Protection", Description = "Disjoncteurs, différentiels et fusibles", DescriptionEn = "Circuit breakers, RCDs and fuses", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "ElectricalServices" },
            new() { Id = 3, Name = "Prises & Interrupteurs", NameEn = "Outlets & Switches", Description = "Prises de courant, interrupteurs et enjoliveurs", DescriptionEn = "Power outlets, switches and faceplates", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "Power" },
            new() { Id = 4, Name = "Éclairage Intérieur", NameEn = "Indoor Lighting", Description = "Ampoules, spots, plafonniers et luminaires", DescriptionEn = "Bulbs, spots, ceiling lights and fixtures", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "Lightbulb" },
            new() { Id = 5, Name = "Éclairage Extérieur", NameEn = "Outdoor Lighting", Description = "Appliques, bornes et projecteurs extérieurs", DescriptionEn = "Wall lights, bollards and outdoor spotlights", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "LightMode" },
            new() { Id = 6, Name = "Tableaux Électriques", NameEn = "Electrical Panels", Description = "Coffrets, tableaux et accessoires de tableau", DescriptionEn = "Enclosures, panels and panel accessories", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "Dashboard" },
            new() { Id = 7, Name = "Domotique", NameEn = "Home Automation", Description = "Prises connectées, thermostats et volets roulants", DescriptionEn = "Smart plugs, thermostats and roller shutters", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "SmartToy" },
            new() { Id = 8, Name = "Outillage Électrique", NameEn = "Electrical Tools", Description = "Tournevis testeurs, pinces et outils de mesure", DescriptionEn = "Test screwdrivers, pliers and measuring tools", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "Build" },
            new() { Id = 9, Name = "Chauffage Électrique", NameEn = "Electric Heating", Description = "Radiateurs, convecteurs et sèche-serviettes", DescriptionEn = "Radiators, convectors and towel warmers", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "Thermostat" },
            new() { Id = 10, Name = "Ventilation & Climatisation", NameEn = "Ventilation & Air Conditioning", Description = "VMC, extracteurs et climatiseurs", DescriptionEn = "Mechanical ventilation, extractors and AC units", ProductCount = 10, SiteType = SiteType.Electrical, Icon = "AcUnit" }
        };
    }

    public static List<Product> GenerateProducts()
    {
        var products = new List<Product>
        {
            // Cat 1: Câbles & Fils
            P(1, 1, "Câble R2V 3G2.5 100m", "R2V 3G2.5 Cable 100m", "Câble rigide 3 conducteurs 2.5mm² pour installation fixe.", "Rigid 3-conductor 2.5mm² cable for fixed installation.", 89.90m, 75.90m, "Nexans", "NEX-R2V325", 40, false, true, true, true, V(1, "100m", "100m", "100m", 0m, 40), V(2, "50m", "50m", "50m", -40m, 60)),
            P(2, 1, "Câble H07V-U 2.5mm² Bleu 100m", "H07V-U 2.5mm² Blue Wire 100m", "Fil rigide bleu pour circuits de puissance.", "Rigid blue wire for power circuits.", 29.90m, null, "Nexans", "NEX-H07VU25B", 80, false, false, false, false, V(3, "100m", "100m", "100m", 0m, 80)),
            P(3, 1, "Gaine ICTA 20mm 100m", "ICTA Conduit 20mm 100m", "Gaine annelée TPC pour encastrement des câbles.", "Corrugated conduit for cable embedding.", 22.90m, 18.90m, "Legrex", "LEG-ICTA20", 60, false, false, false, true, V(4, "100m", "100m", "100m", 0m, 60), V(5, "25m", "25m", "25m", -15m, 90)),
            P(4, 1, "Câble Ethernet Cat6 UTP 100m", "Cat6 UTP Ethernet Cable 100m", "Câble réseau catégorie 6 pour installation domotique et informatique.", "Category 6 network cable for home automation and IT.", 59.90m, null, "Belden", "BEL-CAT6100", 35, true, false, false, false, V(6, "100m", "100m", "100m", 0m, 35)),
            P(5, 1, "Câble coaxial 17VATC 100m", "17VATC Coaxial Cable 100m", "Câble coaxial blindé pour antenne TV et satellite.", "Shielded coaxial cable for TV antenna and satellite.", 35.90m, 29.90m, "Nexans", "NEX-17VATC", 45, false, false, false, true, V(7, "100m", "100m", "100m", 0m, 45), V(8, "25m", "25m", "25m", -25m, 70)),
            P(6, 1, "Câble souple H07RN-F 3G2.5 50m", "H07RN-F 3G2.5 Flexible Cable 50m", "Câble souple caoutchouc pour usage extérieur et chantier.", "Flexible rubber cable for outdoor and construction use.", 75.00m, null, "Nexans", "NEX-H07RNF", 25, false, true, false, false, V(9, "50m", "50m", "50m", 0m, 25)),
            P(7, 1, "Câble téléphone 298 4P 100m", "Telephone Cable 298 4P 100m", "Câble téléphonique 4 paires pour liaison intérieure.", "4-pair telephone cable for interior connection.", 19.90m, 15.90m, "Nexans", "NEX-TEL4P", 50, false, false, false, true, V(10, "100m", "100m", "100m", 0m, 50)),
            P(8, 1, "Câble R2V 5G1.5 50m", "R2V 5G1.5 Cable 50m", "Câble 5 conducteurs 1.5mm² pour volets roulants et VMC.", "5-conductor 1.5mm² cable for roller shutters and ventilation.", 55.00m, null, "Nexans", "NEX-R2V5G15", 30, true, false, false, false, V(11, "50m", "50m", "50m", 0m, 30)),
            P(9, 1, "Câble bus KNX 2P 100m", "KNX Bus Cable 2P 100m", "Câble bus EIB/KNX pour installation domotique.", "EIB/KNX bus cable for home automation installation.", 95.00m, null, "Hager", "HAG-KNX2P", 20, false, false, false, false, V(12, "100m", "100m", "100m", 0m, 20)),
            P(10, 1, "Prolongateur 25m 3G1.5 IP44", "Extension Cord 25m 3G1.5 IP44", "Enrouleur prolongateur professionnel résistant aux projections.", "Professional extension reel splash-resistant.", 39.90m, 33.90m, "Brennenstuhl", "BRS-P25", 40, false, true, false, true, V(13, "25m", "25m", "25m", 0m, 40), V(14, "50m", "50m", "50m", 20m, 20)),

            // Cat 2: Disjoncteurs & Protection
            P(11, 2, "Disjoncteur Legrand DX³ 20A courbe C", "Legrand DX3 20A Circuit Breaker Curve C", "Disjoncteur modulaire unipolaire+neutre 20A pour prises.", "Single-pole+neutral modular circuit breaker 20A for outlets.", 12.90m, 10.50m, "Legrand", "LEG-DX320A", 100, false, true, true, true, V(15, "Uni+N 20A", "SP+N 20A", "20A", 0m, 100)),
            P(12, 2, "Disjoncteur Legrand DX³ 16A courbe C", "Legrand DX3 16A Circuit Breaker", "Disjoncteur modulaire uni+neutre 16A pour éclairage.", "Single-pole+neutral circuit breaker 16A for lighting.", 12.90m, null, "Legrand", "LEG-DX316A", 90, false, true, false, false, V(16, "Uni+N 16A", "SP+N 16A", "16A", 0m, 90)),
            P(13, 2, "Interrupteur différentiel Legrand 63A 30mA Type AC", "Legrand 63A 30mA RCD Type AC", "Interrupteur différentiel 2P 63A sensibilité 30mA.", "2-pole 63A RCD with 30mA sensitivity.", 45.90m, 39.90m, "Legrand", "LEG-ID63AC", 50, false, true, false, true, V(17, "Type AC", "Type AC", "AC", 0m, 50)),
            P(14, 2, "Interrupteur différentiel Schneider 40A 30mA Type A", "Schneider 40A 30mA RCD Type A", "Différentiel type A pour circuits spécialisés (plaque, lave-linge).", "Type A RCD for dedicated circuits (cooktop, washing machine).", 65.00m, null, "Schneider Electric", "SCH-ID40A", 35, true, false, false, false, V(18, "Type A", "Type A", "A", 0m, 35)),
            P(15, 2, "Disjoncteur Schneider iC60N 32A courbe C", "Schneider iC60N 32A Circuit Breaker", "Disjoncteur 32A pour circuits spécialisés (four, plaque).", "32A breaker for dedicated circuits (oven, cooktop).", 18.90m, null, "Schneider Electric", "SCH-IC60N32", 60, false, false, false, false, V(19, "Uni+N 32A", "SP+N 32A", "32A", 0m, 60)),
            P(16, 2, "Parafoudre Hager SPN115", "Hager SPN115 Surge Protector", "Parafoudre type 2 monophasé pour tableau principal.", "Type 2 single-phase surge protector for main panel.", 89.00m, 75.00m, "Hager", "HAG-SPN115", 25, false, false, false, true, V(20, "Standard", "Standard", "Standard", 0m, 25)),
            P(17, 2, "Disjoncteur différentiel Legrand DX³ 20A 30mA", "Legrand DX3 20A 30mA RCBO", "Disjoncteur différentiel combiné 1P+N 20A 30mA.", "Combined RCBO 1P+N 20A 30mA.", 55.00m, null, "Legrand", "LEG-DD20A", 30, true, true, false, false, V(21, "Type AC", "Type AC", "AC", 0m, 30)),
            P(18, 2, "Interrupteur sectionneur Legrand 63A", "Legrand 63A Isolator Switch", "Interrupteur de coupure générale en tête de tableau.", "Main isolator switch at panel head.", 22.90m, 18.90m, "Legrand", "LEG-IS63", 40, false, false, false, true, V(22, "2P 63A", "2P 63A", "63A", 0m, 40)),
            P(19, 2, "Fusible cylindrique 10A 8.5x31.5", "10A Cylindrical Fuse 8.5x31.5", "Lot de 10 fusibles cylindriques avec voyant de fusion.", "Pack of 10 cylindrical fuses with blown indicator.", 5.90m, null, "Legrand", "LEG-FUS10A", 100, false, false, false, false, V(23, "Lot de 10", "Pack of 10", "x10", 0m, 100)),
            P(20, 2, "Contacteur jour/nuit Legrand 25A", "Legrand 25A Day/Night Contactor", "Contacteur heures creuses pour ballon d'eau chaude.", "Off-peak hours contactor for water heater.", 29.90m, 24.90m, "Legrand", "LEG-CJN25", 45, false, true, false, true, V(24, "Standard", "Standard", "Standard", 0m, 45)),

            // Cat 3: Prises & Interrupteurs
            P(21, 3, "Prise Legrand Céliane Blanc", "Legrand Celiane White Outlet", "Prise de courant 2P+T 16A avec terre, finition blanc.", "2P+E 16A power outlet with earth, white finish.", 8.90m, null, "Legrand", "LEG-CEL-P", 120, false, true, false, false, V(25, "Blanc", "White", "Blanc", 0m, 120), V(26, "Titane", "Titanium", "Titane", 2m, 60)),
            P(22, 3, "Interrupteur Legrand Céliane va-et-vient", "Legrand Celiane Two-Way Switch", "Interrupteur va-et-vient 10A, mécanisme + enjoliveur blanc.", "10A two-way switch, mechanism + white trim plate.", 7.90m, 6.50m, "Legrand", "LEG-CEL-VV", 100, false, true, false, true, V(27, "Blanc", "White", "Blanc", 0m, 100)),
            P(23, 3, "Prise Schneider Odace Blanc", "Schneider Odace White Outlet", "Prise 2P+T encastrée avec volet et connexion auto.", "2P+E flush-mounted outlet with shutter and auto connection.", 6.90m, null, "Schneider Electric", "SCH-ODA-P", 90, false, false, false, false, V(28, "Blanc", "White", "Blanc", 0m, 90)),
            P(24, 3, "Double prise Legrand Mosaic 2×2P+T", "Legrand Mosaic 2x2P+E Double Outlet", "Double prise horizontale pour boîte d'encastrement.", "Double horizontal outlet for flush box.", 14.90m, 12.50m, "Legrand", "LEG-MOS-2P", 70, false, false, true, true, V(29, "Blanc", "White", "Blanc", 0m, 70)),
            P(25, 3, "Prise étanche Plexo IP55", "Plexo IP55 Weatherproof Outlet", "Prise extérieure avec clapet et étanchéité IP55.", "Outdoor outlet with flap and IP55 waterproofing.", 12.90m, null, "Legrand", "LEG-PLEX-P", 50, true, false, false, false, V(30, "Gris", "Grey", "Gris", 0m, 50)),
            P(26, 3, "Variateur Legrand Céliane 400W", "Legrand Celiane 400W Dimmer", "Variateur rotatif compatible LED et halogène.", "Rotary dimmer compatible with LED and halogen.", 35.00m, 29.00m, "Legrand", "LEG-CEL-VAR", 30, false, false, false, true, V(31, "Blanc", "White", "Blanc", 0m, 30)),
            P(27, 3, "Prise USB double Legrand", "Legrand Double USB Outlet", "Prise encastrée 2 USB-A 2.4A pour recharge rapide.", "Flush-mounted 2x USB-A 2.4A for fast charging.", 25.90m, null, "Legrand", "LEG-USB2", 40, true, false, false, false, V(32, "Blanc", "White", "Blanc", 0m, 40)),
            P(28, 3, "Prise TV/SAT Legrand Céliane", "Legrand Celiane TV/SAT Outlet", "Prise coaxiale TV-Satellite encastrée.", "Flush-mounted TV-Satellite coaxial outlet.", 15.90m, 12.90m, "Legrand", "LEG-CEL-TV", 35, false, false, false, true, V(33, "Blanc", "White", "Blanc", 0m, 35)),
            P(29, 3, "Interrupteur automatique Legrand", "Legrand Automatic Switch", "Détecteur de mouvement 3 fils avec minuterie réglable.", "3-wire motion detector with adjustable timer.", 45.00m, null, "Legrand", "LEG-AUTO", 25, false, false, false, false, V(34, "Blanc", "White", "Blanc", 0m, 25)),
            P(30, 3, "Plaque triple Legrand Céliane", "Legrand Celiane Triple Plate", "Plaque 3 postes horizontale finition verre Miroir.", "3-gang horizontal plate glass Mirror finish.", 18.90m, 15.90m, "Legrand", "LEG-CEL-P3", 45, false, true, false, true, V(35, "Blanc", "White", "Blanc", 0m, 45), V(36, "Verre Miroir", "Mirror Glass", "Miroir", 12m, 20)),

            // Cat 4: Éclairage Intérieur
            P(31, 4, "Ampoule LED E27 10W 2700K", "LED Bulb E27 10W 2700K", "Ampoule LED blanc chaud équivalent 75W, 1055 lumens.", "Warm white LED bulb equivalent to 75W, 1055 lumens.", 3.90m, 2.90m, "Philips", "PHI-LED10W", 200, false, true, true, true, V(37, "Lot de 1", "Single", "x1", 0m, 200), V(38, "Lot de 6", "6-Pack", "x6", 16m, 80)),
            P(32, 4, "Spot encastré LED GU10 5W", "LED Recessed Spot GU10 5W", "Spot LED orientable blanc chaud avec transformateur intégré.", "Adjustable warm white LED spot with integrated transformer.", 8.90m, null, "Philips", "PHI-SPOTGU10", 80, false, false, false, false, V(39, "Blanc", "White", "Blanc", 0m, 80), V(40, "Nickel", "Nickel", "Nickel", 2m, 50)),
            P(33, 4, "Plafonnier LED rond 24W", "Round LED Ceiling Light 24W", "Plafonnier slim 2400 lumens avec driver intégré, Ø40cm.", "2400 lumen slim ceiling light with integrated driver, Ø40cm.", 29.90m, 24.90m, "Ledvance", "LED-PLF24", 35, true, false, false, true, V(41, "4000K", "4000K", "4000K", 0m, 35), V(42, "3000K", "3000K", "3000K", 0m, 30)),
            P(34, 4, "Bandeau LED 5m Blanc Chaud", "LED Strip 5m Warm White", "Ruban LED autocollant 300 LEDs avec alimentation 12V.", "Self-adhesive LED strip 300 LEDs with 12V power supply.", 24.90m, null, "Paulmann", "PAU-BAND5M", 40, false, false, false, false, V(43, "Blanc chaud", "Warm white", "2700K", 0m, 40), V(44, "Multicolore RGB", "RGB Multicolor", "RGB", 10m, 25)),
            P(35, 4, "Suspension luminaire E27 noir", "Pendant Light E27 Black", "Suspension design industriel avec câble textile 1.5m.", "Industrial design pendant with 1.5m textile cable.", 19.90m, 15.90m, "Eglo", "EGL-SUSP", 30, false, true, false, true, V(45, "Noir", "Black", "Noir", 0m, 30), V(46, "Cuivre", "Copper", "Cuivre", 5m, 18)),
            P(36, 4, "Réglette LED T5 60cm 8W", "LED T5 Batten 60cm 8W", "Réglette sous meuble 800 lumens avec interrupteur intégré.", "Under-cabinet batten 800 lumens with integrated switch.", 12.90m, null, "Osram", "OSR-T560", 55, false, false, false, false, V(47, "4000K", "4000K", "4000K", 0m, 55)),
            P(37, 4, "Lampe de bureau LED tactile", "LED Touch Desk Lamp", "Lampe articulée avec 5 intensités et 3 températures de couleur.", "Articulated lamp with 5 brightness levels and 3 color temperatures.", 35.00m, 29.00m, "Aluminor", "ALU-LBTACT", 25, true, false, false, true, V(48, "Noir", "Black", "Noir", 0m, 25), V(49, "Blanc", "White", "Blanc", 0m, 20)),
            P(38, 4, "Ampoule LED filament E27 vintage", "Vintage Filament LED Bulb E27", "Ampoule déco filament ambrée 4W forme Edison ST64.", "Amber decorative filament bulb 4W Edison shape ST64.", 6.90m, null, "Philips", "PHI-FILM4W", 65, false, true, false, false, V(50, "2200K ambrée", "2200K amber", "2200K", 0m, 65)),
            P(39, 4, "Hublot LED rond IP65 18W", "LED Round Bulkhead IP65 18W", "Hublot étanche pour salle de bain et extérieur couvert.", "Waterproof bulkhead for bathroom and covered outdoor.", 18.90m, 14.90m, "Sarlam", "SAR-HUB18", 40, false, false, false, true, V(51, "4000K", "4000K", "4000K", 0m, 40)),
            P(40, 4, "Spot sur rail LED 20W noir", "LED Track Spot 20W Black", "Spot orientable sur rail pour commerce et habitat.", "Adjustable track spot for retail and residential.", 29.90m, null, "SLV", "SLV-RAIL20", 20, false, false, false, false, V(52, "Noir", "Black", "Noir", 0m, 20), V(53, "Blanc", "White", "Blanc", 0m, 15)),

            // Cat 5: Éclairage Extérieur
            P(41, 5, "Applique extérieure LED 12W IP65", "LED Outdoor Wall Light 12W IP65", "Applique murale anthracite avec double faisceau haut/bas.", "Anthracite wall light with dual up/down beam.", 32.00m, 27.00m, "Philips", "PHI-APPEXT", 25, true, true, false, true, V(54, "Anthracite", "Anthracite", "Anthracite", 0m, 25)),
            P(42, 5, "Projecteur LED 30W IP65", "LED Floodlight 30W IP65", "Projecteur extérieur 2700 lumens avec détecteur de mouvement.", "Outdoor floodlight 2700 lumens with motion detector.", 35.90m, null, "Ledvance", "LED-PROJ30", 30, false, true, false, false, V(55, "Noir", "Black", "Noir", 0m, 30)),
            P(43, 5, "Borne solaire LED jardin", "Solar LED Garden Bollard", "Borne solaire automatique avec batterie Li-Ion rechargeable.", "Automatic solar bollard with rechargeable Li-Ion battery.", 19.90m, 15.90m, "Inspire", "INS-BSOL", 50, false, false, true, true, V(56, "Noir", "Black", "Noir", 0m, 50)),
            P(44, 5, "Guirlande LED extérieure 10m", "Outdoor LED String Lights 10m", "Guirlande festive IP44 avec 20 ampoules LED blanc chaud.", "IP44 festive string lights with 20 warm white LED bulbs.", 24.90m, null, "Blachère", "BLA-GUIR10", 35, true, false, false, false, V(57, "Blanc chaud", "Warm white", "2700K", 0m, 35)),
            P(45, 5, "Lampadaire solaire puissant 1500lm", "Powerful Solar Lamp Post 1500lm", "Candélabre solaire avec panneau 25W et télécommande.", "Solar lamp post with 25W panel and remote control.", 89.00m, 75.00m, "Steinel", "STE-LSS1500", 15, false, false, false, true, V(58, "Noir", "Black", "Noir", 0m, 15)),
            P(46, 5, "Spot à piquer LED solaire", "Solar LED Spike Spot", "Spot de jardin solaire orientable avec piquet.", "Adjustable solar garden spot with ground spike.", 12.90m, null, "Inspire", "INS-SPSOL", 60, false, false, false, false, V(59, "Noir", "Black", "Noir", 0m, 60)),
            P(47, 5, "Projecteur LED 50W IP65 avec détecteur", "LED Floodlight 50W IP65 with Sensor", "Projecteur puissant avec détecteur de mouvement 12m.", "Powerful floodlight with 12m motion sensor.", 49.90m, 42.90m, "Brennenstuhl", "BRS-PROJ50", 20, false, true, false, true, V(60, "Noir", "Black", "Noir", 0m, 20)),
            P(48, 5, "Applique solaire LED détecteur", "Solar LED Wall Light with Sensor", "Applique solaire grand angle avec détecteur crépusculaire.", "Wide-angle solar wall light with dusk sensor.", 22.90m, null, "Steinel", "STE-ASLD", 35, false, false, false, false, V(61, "Noir", "Black", "Noir", 0m, 35)),
            P(49, 5, "Ruban LED extérieur IP67 5m", "Outdoor LED Strip IP67 5m", "Ruban LED étanche silicone pour terrasse et contour piscine.", "Silicone waterproof LED strip for terrace and pool surround.", 39.90m, 33.90m, "Paulmann", "PAU-RBEXT5", 22, false, false, false, true, V(62, "Blanc chaud", "Warm white", "2700K", 0m, 22), V(63, "RGB", "RGB", "RGB", 15m, 15)),
            P(50, 5, "Lanterne solaire décorative", "Decorative Solar Lantern", "Lanterne suspendue avec bougie LED et effet flamme.", "Hanging lantern with LED candle and flame effect.", 15.90m, null, "Inspire", "INS-LSOL", 40, true, false, false, false, V(64, "Noir", "Black", "Noir", 0m, 40)),

            // Cat 6: Tableaux Électriques
            P(51, 6, "Coffret Legrand Drivia 13 modules 2 rangées", "Legrand Drivia Panel 13 Modules 2 Rows", "Coffret d'habillage avec porte opaque pour tableau DIY.", "Trim enclosure with opaque door for DIY panel.", 35.90m, 29.90m, "Legrand", "LEG-DRIV2R", 30, false, true, false, true, V(65, "2 rangées", "2 rows", "2R", 0m, 30)),
            P(52, 6, "Coffret Legrand Drivia 13 modules 3 rangées", "Legrand Drivia Panel 13 Modules 3 Rows", "Coffret 3 rangées pour installation T3-T4 complète.", "3-row enclosure for complete T3-T4 installation.", 45.90m, null, "Legrand", "LEG-DRIV3R", 25, false, true, false, false, V(66, "3 rangées", "3 rows", "3R", 0m, 25)),
            P(53, 6, "Coffret Schneider Resi9 2 rangées", "Schneider Resi9 Panel 2 Rows", "Tableau électrique pré-équipé avec borniers et peigne.", "Pre-equipped electrical panel with terminals and comb.", 42.00m, 35.00m, "Schneider Electric", "SCH-RESI2R", 20, true, false, false, true, V(67, "2 rangées", "2 rows", "2R", 0m, 20)),
            P(54, 6, "Peigne d'alimentation horizontal Legrand", "Legrand Horizontal Comb Busbar", "Peigne horizontal 1P+N pour connexion rapide des modules.", "Horizontal 1P+N comb busbar for quick module connection.", 15.90m, null, "Legrand", "LEG-PEIGNH", 60, false, false, false, false, V(68, "13 modules", "13 modules", "13M", 0m, 60)),
            P(55, 6, "Bornier de terre 25mm²", "25mm² Earth Terminal", "Bornier de terre rail DIN pour tableau électrique.", "DIN rail earth terminal for electrical panel.", 8.90m, 6.90m, "Legrand", "LEG-BORNT", 80, false, false, false, true, V(69, "Standard", "Standard", "Standard", 0m, 80)),
            P(56, 6, "Coffret de communication Grade 2", "Grade 2 Communication Panel", "Coffret multimédia pour distribution TV, RJ45 et fibre.", "Multimedia enclosure for TV, RJ45 and fiber distribution.", 89.00m, null, "Legrand", "LEG-COMM-G2", 15, false, false, false, false, V(70, "Standard", "Standard", "Standard", 0m, 15)),
            P(57, 6, "GTL (Gaine Technique Logement) 2.60m", "GTL Housing Technical Duct 2.60m", "Goulotte technique pour passage des câbles du tableau.", "Technical trunking for panel cable routing.", 42.00m, 35.00m, "Legrand", "LEG-GTL260", 22, false, false, false, true, V(71, "Blanc", "White", "Blanc", 0m, 22)),
            P(58, 6, "Porte transparente Drivia 2 rangées", "Drivia Transparent Door 2 Rows", "Porte de coffret avec vision directe sur les modules.", "Enclosure door with direct view of modules.", 18.90m, null, "Legrand", "LEG-PORTD2", 35, false, false, false, false, V(72, "Standard", "Standard", "Standard", 0m, 35)),
            P(59, 6, "Kit de mise à la terre", "Earthing Kit", "Kit complet : piquet, câble cuivre 25mm² et barrette de coupure.", "Complete kit: rod, 25mm² copper cable and disconnect bar.", 35.00m, 29.00m, "Legrand", "LEG-KMAT", 25, true, false, false, true, V(73, "Standard", "Standard", "Standard", 0m, 25)),
            P(60, 6, "Tableau pré-câblé T2 Legrand", "Legrand Pre-Wired T2 Panel", "Tableau complet pré-câblé pour logement T2, NF C 15-100.", "Complete pre-wired panel for T2 housing, NF C 15-100 compliant.", 189.00m, 159.00m, "Legrand", "LEG-PRT2", 12, false, false, true, true, V(74, "Standard", "Standard", "Standard", 0m, 12)),

            // Cat 7: Domotique
            P(61, 7, "Prise connectée Legrand with Netatmo", "Legrand Connected Outlet with Netatmo", "Prise 16A pilotable par app avec mesure de consommation.", "16A app-controlled outlet with consumption monitoring.", 69.00m, 59.00m, "Legrand", "LEG-WNET-P", 25, true, true, false, true, V(75, "Blanc", "White", "Blanc", 0m, 25)),
            P(62, 7, "Thermostat connecté Netatmo", "Netatmo Smart Thermostat", "Thermostat intelligent avec programme auto-adapt et contrôle vocal.", "Smart thermostat with auto-adapt schedule and voice control.", 179.00m, null, "Netatmo", "NET-THERM", 20, false, true, false, false, V(76, "Standard", "Standard", "Standard", 0m, 20)),
            P(63, 7, "Interrupteur connecté Legrand with Netatmo", "Legrand Connected Switch with Netatmo", "Interrupteur va-et-vient connecté avec commande vocale.", "Connected two-way switch with voice control.", 59.00m, 49.00m, "Legrand", "LEG-WNET-I", 30, false, false, false, true, V(77, "Blanc", "White", "Blanc", 0m, 30)),
            P(64, 7, "Module volet roulant connecté Delta Dore", "Delta Dore Connected Roller Shutter Module", "Module Tydom pour pilotage des volets roulants à distance.", "Tydom module for remote roller shutter control.", 59.00m, null, "Delta Dore", "DD-VOLCON", 20, true, false, false, false, V(78, "Standard", "Standard", "Standard", 0m, 20)),
            P(65, 7, "Caméra intérieure connectée Netatmo", "Netatmo Smart Indoor Camera", "Caméra de sécurité avec reconnaissance faciale et alertes.", "Security camera with facial recognition and alerts.", 199.00m, 169.00m, "Netatmo", "NET-CAM", 18, false, false, true, true, V(79, "Standard", "Standard", "Standard", 0m, 18)),
            P(66, 7, "Détecteur fumée connecté Netatmo", "Netatmo Smart Smoke Alarm", "Détecteur de fumée intelligent avec alerte smartphone.", "Smart smoke detector with smartphone alert.", 99.00m, null, "Netatmo", "NET-FUMEE", 30, false, false, false, false, V(80, "Standard", "Standard", "Standard", 0m, 30)),
            P(67, 7, "Ampoule connectée Philips Hue E27", "Philips Hue Smart Bulb E27", "Ampoule LED connectée White and Color 9W, 16 millions de couleurs.", "Connected White and Color 9W LED bulb, 16 million colors.", 49.90m, 39.90m, "Philips", "PHI-HUE-E27", 40, false, true, false, true, V(81, "White and Color", "White and Color", "WC", 0m, 40), V(82, "White Ambiance", "White Ambiance", "WA", -15m, 50)),
            P(68, 7, "Pont Philips Hue Bridge", "Philips Hue Bridge", "Passerelle Zigbee pour contrôler jusqu'à 50 ampoules Hue.", "Zigbee gateway to control up to 50 Hue bulbs.", 49.90m, null, "Philips", "PHI-HUE-BR", 25, false, false, false, false, V(83, "Standard", "Standard", "Standard", 0m, 25)),
            P(69, 7, "Sonnette vidéo connectée Ring", "Ring Video Doorbell", "Sonnette vidéo HD avec détection de mouvement et vision nocturne.", "HD video doorbell with motion detection and night vision.", 99.00m, 85.00m, "Ring", "RNG-VD", 22, true, false, false, true, V(84, "Nickel satiné", "Satin Nickel", "Nickel", 0m, 22)),
            P(70, 7, "Prise connectée TP-Link Tapo P110", "TP-Link Tapo P110 Smart Plug", "Prise WiFi avec suivi de consommation en temps réel.", "WiFi plug with real-time energy monitoring.", 14.90m, null, "TP-Link", "TPL-P110", 60, false, false, false, false, V(85, "Standard", "Standard", "Standard", 0m, 60)),

            // Cat 8: Outillage Électrique
            P(71, 8, "Multimètre digital Fluke 117", "Fluke 117 Digital Multimeter", "Multimètre TRMS avec détection de tension sans contact.", "True-RMS multimeter with non-contact voltage detection.", 189.00m, 165.00m, "Fluke", "FLK-117", 15, true, true, false, true, V(86, "Standard", "Standard", "Standard", 0m, 15)),
            P(72, 8, "Tournevis testeur Wera", "Wera Voltage Tester Screwdriver", "Tournevis testeur de phase 100-250V avec lame isolée.", "Phase voltage tester screwdriver 100-250V with insulated blade.", 8.90m, null, "Wera", "WER-TEST", 80, false, true, false, false, V(87, "Standard", "Standard", "Standard", 0m, 80)),
            P(73, 8, "Pince coupante diagonale VDE 160mm", "VDE Diagonal Cutting Pliers 160mm", "Pince coupante isolée 1000V pour travaux sous tension.", "1000V insulated cutting pliers for live working.", 25.90m, 21.90m, "Knipex", "KNP-DIG160", 40, false, false, false, true, V(88, "Standard", "Standard", "Standard", 0m, 40)),
            P(74, 8, "Pince à dénuder automatique Jokari", "Jokari Automatic Wire Stripper", "Pince à dénuder auto-ajustable 0.2-6mm².", "Auto-adjustable wire stripper 0.2-6mm².", 19.90m, null, "Jokari", "JOK-DEN", 35, false, false, false, false, V(89, "Standard", "Standard", "Standard", 0m, 35)),
            P(75, 8, "Coffret embouts isolés", "Insulated Ferrule Kit", "Coffret 800 embouts de câblage avec pince à sertir.", "800-piece wiring ferrule kit with crimping tool.", 39.90m, 33.90m, "Weidmüller", "WDM-EMBKIT", 25, false, true, false, true, V(90, "Standard", "Standard", "Standard", 0m, 25)),
            P(76, 8, "Détecteur de câbles et métaux", "Cable and Metal Detector", "Détecteur mural pour câbles sous tension et canalisations.", "Wall detector for live cables and pipes.", 49.90m, null, "Bosch", "BOS-DET", 20, true, false, false, false, V(91, "Standard", "Standard", "Standard", 0m, 20)),
            P(77, 8, "Niveau laser vert Bosch", "Bosch Green Laser Level", "Niveau laser croix autonivelant avec portée 15m.", "Self-leveling cross-line laser level with 15m range.", 79.00m, 65.00m, "Bosch", "BOS-LASER", 18, false, false, false, true, V(92, "Standard", "Standard", "Standard", 0m, 18)),
            P(78, 8, "Coffret tournevis isolés 1000V Wera", "Wera 1000V Insulated Screwdriver Set", "Coffret 7 tournevis VDE plat et cruciforme.", "7-piece VDE flat and Phillips insulated screwdriver set.", 55.00m, null, "Wera", "WER-VDE7", 22, false, true, false, false, V(93, "Standard", "Standard", "Standard", 0m, 22)),
            P(79, 8, "Testeur de prise Chauvin Arnoux", "Chauvin Arnoux Socket Tester", "Contrôleur de prise avec test différentiel 30mA.", "Socket tester with 30mA RCD test.", 35.00m, 29.00m, "Chauvin Arnoux", "CA-TESTP", 30, false, false, false, true, V(94, "Standard", "Standard", "Standard", 0m, 30)),
            P(80, 8, "Sac à outils électricien", "Electrician Tool Bag", "Sacoche professionnelle 20 compartiments fond renforcé.", "Professional tool bag 20 compartments reinforced bottom.", 45.00m, null, "Facom", "FAC-SACEL", 15, false, false, false, false, V(95, "Standard", "Standard", "Standard", 0m, 15)),

            // Cat 9: Chauffage Électrique
            P(81, 9, "Radiateur inertie sèche 1500W", "Dry Inertia Radiator 1500W", "Radiateur à inertie céramique programmable avec écran LCD.", "Programmable ceramic inertia radiator with LCD display.", 249.00m, 209.00m, "Atlantic", "ATL-INE1500", 20, true, true, false, true, V(96, "1500W", "1500W", "1500W", 0m, 20), V(97, "1000W", "1000W", "1000W", -50m, 25)),
            P(82, 9, "Radiateur inertie fluide 1000W", "Fluid Inertia Radiator 1000W", "Radiateur à fluide caloporteur avec chaleur douce et homogène.", "Heat transfer fluid radiator with gentle and even heat.", 199.00m, null, "Acova", "ACO-INF1000", 18, false, true, false, false, V(98, "1000W", "1000W", "1000W", 0m, 18)),
            P(83, 9, "Panneau rayonnant 1500W", "Radiant Panel 1500W", "Panneau rayonnant programmable très plat, épaisseur 7.5cm.", "Ultra-slim programmable radiant panel, 7.5cm thick.", 149.00m, 125.00m, "Atlantic", "ATL-RAY1500", 25, false, false, false, true, V(99, "1500W", "1500W", "1500W", 0m, 25), V(100, "1000W", "1000W", "1000W", -30m, 30)),
            P(84, 9, "Convecteur électrique 2000W", "Electric Convector 2000W", "Convecteur mural silencieux avec thermostat mécanique.", "Silent wall-mounted convector with mechanical thermostat.", 59.00m, null, "Atlantic", "ATL-CONV2000", 40, false, false, false, false, V(101, "2000W", "2000W", "2000W", 0m, 40)),
            P(85, 9, "Sèche-serviettes soufflant 1500W", "Towel Warmer with Fan 1500W", "Sèche-serviettes électrique avec soufflerie 500W boost.", "Electric towel warmer with 500W fan boost.", 199.00m, 169.00m, "Sauter", "SAU-SS1500", 15, true, false, true, true, V(102, "Blanc", "White", "Blanc", 0m, 15)),
            P(86, 9, "Radiateur à bain d'huile 2500W", "Oil-Filled Radiator 2500W", "Radiateur mobile 11 éléments avec minuterie 24h.", "Mobile 11-element radiator with 24h timer.", 79.00m, null, "De'Longhi", "DLG-HUILE2500", 22, false, false, false, false, V(103, "2500W", "2500W", "2500W", 0m, 22)),
            P(87, 9, "Cheminée électrique décorative", "Decorative Electric Fireplace", "Cheminée murale avec effet flamme LED et chauffage 2000W.", "Wall-mounted fireplace with LED flame effect and 2000W heating.", 349.00m, 299.00m, "Carrera", "CAR-CHEMEL", 10, false, false, false, true, V(104, "Standard", "Standard", "Standard", 0m, 10)),
            P(88, 9, "Radiateur sèche-serviettes pivotant", "Pivoting Towel Warmer Radiator", "Sèche-serviettes eau chaude pivotant en acier chromé.", "Pivoting hot water towel warmer in chrome steel.", 159.00m, null, "Acova", "ACO-SSPIV", 14, false, true, false, false, V(105, "Chromé", "Chrome", "Chrome", 0m, 14)),
            P(89, 9, "Plancher chauffant électrique 5m²", "Electric Underfloor Heating 5m²", "Trame chauffante en nappe pour rénovation, 150W/m².", "Heating mat for renovation, 150W/m².", 129.00m, 109.00m, "Thermor", "THE-PCH5", 16, false, false, false, true, V(106, "5m²", "5m²", "5m²", 0m, 16), V(107, "10m²", "10m²", "10m²", 80m, 10)),
            P(90, 9, "Soufflant céramique 2000W", "Ceramic Fan Heater 2000W", "Chauffage soufflant d'appoint avec oscillation et minuterie.", "Supplementary fan heater with oscillation and timer.", 39.90m, null, "Rowenta", "ROW-SOUF2000", 35, false, false, false, false, V(108, "Standard", "Standard", "Standard", 0m, 35)),

            // Cat 10: Ventilation & Climatisation
            P(91, 10, "VMC simple flux auto Aldes", "Aldes Single Flow Self-Adjusting MEV", "VMC autoréglable 2 vitesses pour T2-T5 avec bouches.", "Self-regulating 2-speed MEV for T2-T5 with vents.", 129.00m, 109.00m, "Aldes", "ALD-VMCAUTO", 20, true, true, true, true, V(109, "Standard", "Standard", "Standard", 0m, 20)),
            P(92, 10, "VMC double flux haut rendement", "High Efficiency Heat Recovery MEV", "VMC double flux avec récupération de chaleur 90%.", "Dual-flow MEV with 90% heat recovery.", 899.00m, null, "Aldes", "ALD-DF90", 8, false, false, false, false, V(110, "Standard", "Standard", "Standard", 0m, 8)),
            P(93, 10, "Extracteur salle de bain 15W", "Bathroom Extractor Fan 15W", "Extracteur silencieux 26dB avec temporisateur et clapet anti-retour.", "Silent 26dB extractor with timer and backdraft shutter.", 39.90m, 33.90m, "Aldes", "ALD-EXTSDB", 35, false, true, false, true, V(111, "Standard", "Standard", "Standard", 0m, 35)),
            P(94, 10, "Climatiseur split inverter 2.5kW", "Inverter Split AC 2.5kW", "Climatiseur réversible chaud/froid pour pièce 25m², classe A++.", "Reversible hot/cold AC for 25m² room, A++ rated.", 599.00m, 499.00m, "Daikin", "DAI-SPLIT25", 10, false, false, true, true, V(112, "2.5kW", "2.5kW", "2.5kW", 0m, 10)),
            P(95, 10, "Climatiseur mobile 2.6kW", "Portable Air Conditioner 2.6kW", "Climatiseur monobloc mobile avec déshumidification 46L/jour.", "Mobile monobloc AC with 46L/day dehumidification.", 399.00m, null, "De'Longhi", "DLG-CLIMOB", 15, true, false, false, false, V(113, "Standard", "Standard", "Standard", 0m, 15)),
            P(96, 10, "Ventilateur colonne tour 45W", "Tower Fan 45W", "Ventilateur colonne silencieux avec oscillation et télécommande.", "Silent tower fan with oscillation and remote control.", 59.00m, 49.00m, "Dyson", "DYS-TOWER45", 28, false, true, false, true, V(114, "Standard", "Standard", "Standard", 0m, 28)),
            P(97, 10, "Bouche VMC hygro cuisine", "Humidity-Sensitive Kitchen MEV Vent", "Bouche d'extraction hygroréglable 10-45 m³/h pour cuisine.", "Humidity-adjustable extract vent 10-45 m³/h for kitchen.", 29.90m, null, "Aldes", "ALD-BCUISINE", 40, false, false, false, false, V(115, "Standard", "Standard", "Standard", 0m, 40)),
            P(98, 10, "Grille de ventilation réglable 150mm", "Adjustable Ventilation Grille 150mm", "Grille d'aération murale avec volet réglable.", "Wall ventilation grille with adjustable shutter.", 5.90m, 4.50m, "Nicoll", "NIC-GRILL150", 80, false, false, false, true, V(116, "Blanc", "White", "Blanc", 0m, 80)),
            P(99, 10, "Déshumidificateur 20L/jour", "Dehumidifier 20L/day", "Déshumidificateur électrique avec hygrostat et mode buanderie.", "Electric dehumidifier with hygrostat and laundry mode.", 199.00m, 169.00m, "De'Longhi", "DLG-DESHUM20", 18, false, false, false, true, V(117, "Standard", "Standard", "Standard", 0m, 18)),
            P(100, 10, "Ventilateur plafond avec lumière LED", "Ceiling Fan with LED Light", "Ventilateur de plafond 3 vitesses avec LED 18W intégrée.", "3-speed ceiling fan with integrated 18W LED.", 89.00m, null, "Westinghouse", "WST-VPCLLED", 14, false, true, false, false, V(118, "Blanc", "White", "Blanc", 0m, 14), V(119, "Nickel", "Nickel", "Nickel", 10m, 10)),
        };

        foreach (var p in products)
        {
            p.SiteType = SiteType.Electrical;
            p.RelatedProductIds = DataSeeder.GetRelatedIds(p.Id, products.Count);
            p.Tags = GenerateTags(p);
        }

        return products;
    }

    private static Product P(int id, int catId, string name, string nameEn, string desc, string descEn,
        decimal price, decimal? promo, string brand, string sku, int stock,
        bool isNew, bool isBestSeller, bool isFeatured, bool isPromo,
        params ProductVariant[] variants)
    {
        return new Product
        {
            Id = id, CategoryId = catId, Name = name, NameEn = nameEn,
            Description = desc, DescriptionEn = descEn, Price = price, PromoPrice = promo,
            Brand = brand, Sku = sku, Stock = stock,
            IsNew = isNew, IsBestSeller = isBestSeller, IsFeatured = isFeatured, IsPromo = isPromo,
            Variants = variants.ToList(),
            CreatedAt = DataSeeder.RandomRecentDate(),
            SiteType = SiteType.Electrical
        };
    }

    private static ProductVariant V(int id, string name, string nameEn, string value, decimal adj, int stock)
        => new() { Id = id, Name = name, NameEn = nameEn, Value = value, PriceAdjustment = adj, Stock = stock };

    private static List<string> GenerateTags(Product p)
    {
        var tags = new List<string> { p.Brand };
        if (p.IsNew) tags.Add("Nouveauté");
        if (p.IsPromo) tags.Add("Promo");
        if (p.IsBestSeller) tags.Add("Best-seller");
        return tags;
    }
}
