import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const screenshots = process.env.RECIPE_UI_ARTIFACTS_DIR;
if (!screenshots) throw new Error('Set RECIPE_UI_ARTIFACTS_DIR to a dedicated artifact directory outside the repository.');
await mkdir(screenshots, { recursive: true });

const targets = await (await fetch('http://127.0.0.1:5187/json/list')).json();
const target = targets.find(target => target.type === 'page');
assert.ok(target?.webSocketDebuggerUrl, 'Start an isolated Chromium browser with a page on debugging port 5187.');
const socket = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(resolve => socket.addEventListener('open', resolve, { once: true }));
let id = 0;
const pending = new Map();
const exceptions = [];
socket.addEventListener('message', ({ data }) => {
  const message = JSON.parse(data);
  if (message.method === 'Runtime.exceptionThrown') exceptions.push(message.params.exceptionDetails.text);
  if (!message.id) return;
  const handler = pending.get(message.id);
  pending.delete(message.id);
  if (message.error) handler.reject(new Error(JSON.stringify(message.error)));
  else handler.resolve(message.result);
});
const cdp = (method, params = {}) => new Promise((resolve, reject) => {
  pending.set(++id, { resolve, reject });
  socket.send(JSON.stringify({ id, method, params }));
});
const evaluate = async expression => {
  const result = await cdp('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
  if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
  return result.result.value;
};
const wait = async (expression, label) => {
  for (let i = 0; i < 200; i++) {
    if (await evaluate(expression)) return;
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  throw new Error(`Timeout: ${label}\n${await evaluate('document.body.innerText')}`);
};
const text = string => `document.body?.innerText.includes(${JSON.stringify(string)})`;
const click = label => evaluate(`(() => {
  const element = [...document.querySelectorAll('button,[role="button"]')].find(el => el.innerText.trim() === ${JSON.stringify(label)});
  if (!element) throw new Error('Missing button: ' + ${JSON.stringify(label)});
  element.click();
})()`);
const clickLabel = label => evaluate(`(() => {
  const element = document.querySelector('[aria-label=' + JSON.stringify(${JSON.stringify(label)}) + ']');
  if (!element) throw new Error('Missing control: ' + ${JSON.stringify(label)});
  element.click();
})()`);
const expanded = label => evaluate(`(() => {
  const element = [...document.querySelectorAll('button')].find(el => el.innerText.trim() === ${JSON.stringify(label)});
  if (!element) throw new Error('Missing section: ' + ${JSON.stringify(label)});
  return element.getAttribute('aria-expanded');
})()`);
const input = (selector, value) => evaluate(`(() => {
  const element = document.querySelector(${JSON.stringify(selector)});
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(element, ${JSON.stringify(value)});
  element.dispatchEvent(new Event('input', { bubbles: true }));
  element.dispatchEvent(new Event('change', { bubbles: true }));
})()`);
const configure = settings => fetch('http://localhost:5185/__test', { method: 'POST', body: JSON.stringify(settings) });
const state = async () => (await fetch('http://localhost:5185/__test')).json();
const count = async path => (await state()).calls.filter(call => call.path.endsWith(path)).length;
const navigate = async (path = '/recipe-basket') => {
  await cdp('Page.navigate', { url: `http://localhost:5186${path}` });
};
const ready = async () => {
  await navigate();
  await wait("!!document.querySelector('#recipe-name')", 'recipe form');
};
const screenshot = async file => {
  await evaluate(`new Promise(resolve => {
    window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
    requestAnimationFrame(() => requestAnimationFrame(resolve));
  })`);
  const image = await cdp('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true });
  await writeFile(join(screenshots, file), Buffer.from(image.data, 'base64'));
};
const prepare = async (recipe = 'Lasagnes') => {
  await click(recipe);
  await click('Préparer ma liste de courses');
  await wait(text('Votre liste à vérifier'), 'preview');
};
await cdp('Runtime.enable');
await cdp('Page.enable');
await cdp('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1100, deviceScaleFactor: 1, mobile: false });
await configure({ site: 'Grocery', available: true, optionsUnavailable: false, planFailures: 0, commitFailures: 0, commitStatus: 503, dropCommitResponses: 0, planDelay: 800, expiryMs: 600000, empty: false });
await ready();
await evaluate("sessionStorage.removeItem('zava-recipe-hidden-session'); sessionStorage.removeItem('zava-recipe-draft'); localStorage.removeItem('zava-recipe-hidden-forever'); localStorage.removeItem('zava-recipe-promotion-dismissed')");
await ready();
assert.equal(await evaluate("document.querySelector('#recipe-name').maxLength"), 200);
assert.equal(await evaluate("document.querySelector('#recipe-servings').value"), '4');
assert.equal(await evaluate("document.querySelector('input[name=\"recipe-brand-preference\"]:checked').value"), 'Mix');
for (const suggestion of ['Lasagnes', 'Blanquette de veau', 'Carbonade', 'Bœuf bourguignon', 'BBQ', 'Repas végétarien', 'Pizza']) assert.equal(await evaluate(text(suggestion)), true);
assert.equal(await count('/commit'), 0);
await screenshot('.recipe-ui-desktop.png');
console.log('PASS initial defaults, suggestions, input limit and no cart mutation');

await click('Lasagnes');
await input('#recipe-servings', '6');
await evaluate("document.querySelector('input[value=\"PrivateLabel\"]').click()");
const beforePlan = await count('/plan');
await click('Préparer ma liste de courses');
await evaluate("document.querySelector('main form button[type=\"submit\"]').click()");
await wait(text('La demande est en cours.'), 'factual progress');
assert.equal(await evaluate("document.querySelector('#recipe-name').disabled"), true);
await wait(text('Votre liste à vérifier'), 'preview');
assert.equal(await count('/plan'), beforePlan + 1);
const submitted = (await state()).calls.filter(call => call.path.endsWith('/plan')).at(-1).body;
assert.deepEqual(submitted, { recipe: 'Lasagnes', servings: 6, brandPreference: 'PrivateLabel', excludedProductIds: [] });
for (const value of ['Paquet de 500 g', '2 paquet(s) / unité(s)', '16,98', 'Noix de muscade', 'Points à vérifier', 'allergènes']) assert.equal(await evaluate(text(value)), true);
assert.equal(await evaluate(text('Produits sélectionnés (4)')), true);
assert.equal(await count('/commit'), 0);
await screenshot('.recipe-ui-preview.png');
console.log('PASS real request payload, duplicate planning guard, honest progress, variants, pack quantities, missing ingredients and warnings');

await input('#recipe-name', 'Blanquette de veau');
await wait(`!(${text('Votre liste à vérifier')})`, 'stale preview cleared');
await input('#recipe-servings', '0');
assert.equal(await evaluate("document.querySelector('main form button[type=\"submit\"]').disabled"), true);
await input('#recipe-servings', '21');
assert.equal(await evaluate("document.querySelector('main form button[type=\"submit\"]').disabled"), true);
await input('#recipe-servings', '1.5');
assert.equal(await evaluate("document.querySelector('main form button[type=\"submit\"]').disabled"), true);
await input('#recipe-servings', '20');
assert.equal(await evaluate("document.querySelector('main form button[type=\"submit\"]').disabled"), false);
await input('#recipe-servings', '4');
await configure({ planFailures: 1 });
await click('Préparer ma liste de courses');
await wait(text('Réessayez la préparation dans un instant.'), 'plan failure');
await click('Réessayer');
await wait(text('Votre liste à vérifier'), 'retry preview');
console.log('PASS stale preview reset, servings 1–20 integer validation and plan error retry');

await configure({ commitFailures: 1 });
const beforeCommit = await count('/commit');
await click('Confirmer et ajouter les produits disponibles');
await evaluate("[...document.querySelectorAll('button')].find(el => el.innerText.includes('Ajout au panier')).click()");
await wait(text('Connexion interrompue pendant la confirmation.'), 'commit failure');
assert.equal(await count('/commit'), beforeCommit + 1);
await click('Réessayer le même ajout');
await wait(text('Les produits de votre recette ont été ajoutés au panier.'), 'commit success');
const commitCalls = (await state()).calls.filter(call => call.path.endsWith('/commit'));
assert.equal(commitCalls.at(-1).body.planId, commitCalls.at(-2).body.planId);
assert.equal((await state()).cart.items[0].variantId, 999);
assert.equal((await state()).cart.itemCount, 7);
assert.equal(await evaluate("document.querySelector('.MuiBadge-badge').innerText"), '7');
assert.equal(await evaluate("[...document.querySelectorAll('button')].find(el => el.innerText.trim() === 'Produits ajoutés').disabled"), true);
console.log('PASS explicit partial confirmation, duplicate commit guard, idempotent retry ID, preserved basket and immediate badge/success notification');

await ready();
await prepare('Carbonade');
const cartBeforeInstantPot = (await state()).cart.itemCount;
await click('Confirmer et ajouter les produits disponibles');
await wait(text('Offre spéciale pour cette recette'), 'carbonade promotion');
assert.equal(await expanded('Offre spéciale pour cette recette (1)'), 'true', 'The recipe promotion cartouche is expanded by default');
assert.equal(await evaluate("document.querySelector('#recipe-total').compareDocumentPosition(document.querySelector('#recipe-promotion-carbonade-instant-pot-button')) & Node.DOCUMENT_POSITION_FOLLOWING"), 4, 'The promotion follows the selected products total');
await wait(text('Instant Pot 921267 Classic Mini 3,8 L'), 'instant pot product loaded');
assert.equal(await evaluate(text('89,99')), true);
assert.equal(await evaluate("!!document.querySelector('img[alt=\"Instant Pot 921267 Classic Mini 3,8 L\"][src$=\"/images/products/Grocery/267/1_medium.jpg\"]')"), true);
await click('Ajouter au panier');
await wait(text('Ajouté au panier'), 'instant pot added');
assert.equal((await state()).cart.itemCount, cartBeforeInstantPot + 7, 'Carbonade products plus the Instant Pot reach the basket');
assert.equal((await state()).cart.items.at(-1).productId, 267);
console.log('PASS Carbonade confirmation shows the Instant Pot promotion expanded by default and can add it to the cart');

await ready();
await prepare('BBQ');
await click('Confirmer et ajouter les produits disponibles');
await wait(text('Weber Compact Kettle 47 cm'), 'BBQ barbecue promotion');
assert.equal(await evaluate("!!document.querySelector('img[alt=\"Weber Compact Kettle 47 cm\"][src$=\"/images/products/Grocery/264/1_medium.jpg\"]')"), true);
await click('Ne plus me proposer ce choix');
await wait(`!(${text('Offre spéciale pour cette recette')})`, 'dismissed BBQ offer');
await ready();
await prepare('BBQ');
await click('Confirmer et ajouter les produits disponibles');
await wait(text('Les produits de votre recette ont été ajoutés au panier.'), 'BBQ commit after dismissal');
assert.equal(await evaluate(text('Weber Compact Kettle 47 cm')), false, 'Dismissed BBQ promotion does not reappear');
console.log('PASS BBQ confirmation shows the barbecue promotion and the dismiss option prevents future prompts');

await configure({ expiryMs: 100 });
await ready();
await prepare();
await wait(text('Cette proposition a expiré.'), 'expired preview');
assert.equal(await evaluate("[...document.querySelectorAll('button')].find(el => el.innerText.startsWith('Confirmer')).disabled"), true);
await configure({ expiryMs: 600000 });
await click('Actualiser la proposition');
await wait(text('Votre liste à vérifier'), 'refreshed preview');
await wait(`!(${text('Cette proposition a expiré.')})`, 'cleared expiration');
console.log('PASS expiration blocks stale confirmation and regeneration restores preview');

for (const commitStatus of [409, 410]) {
  await configure({ commitFailures: 1, commitStatus });
  await ready();
  await prepare();
  await click('Confirmer et ajouter les produits disponibles');
  await wait(text('Ce panier recette a expiré ou la boutique a changé.'), `HTTP ${commitStatus} conflict`);
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(el => el.innerText.startsWith('Confirmer')).disabled"), true);
  assert.equal(await evaluate(text('Réessayer le même ajout')), false);
  await click('Actualiser la proposition');
  await wait(text('Votre liste à vérifier'), 'new preview after conflict');
  await wait(`!(${text('Ce panier recette a expiré ou la boutique a changé.')})`, 'conflict cleared');
}
console.log('PASS 409/410 require a fresh preview instead of repeating rejected commits');

await configure({ commitStatus: 503, dropCommitResponses: 1 });
await ready();
await prepare();
const cartBeforeLostResponse = (await state()).cart.itemCount;
await click('Confirmer et ajouter les produits disponibles');
await wait(text('Réessayer le même ajout'), 'lost successful commit response');
assert.equal((await state()).cart.itemCount, cartBeforeLostResponse + 6);
await configure({ commitFailures: 1, commitStatus: 429 });
await click('Réessayer le même ajout');
await wait(text('Connexion interrompue pendant la confirmation.'), 'rate limited uncertain retry');
await click('Réessayer le même ajout');
await wait(text('Les produits de votre recette ont été ajoutés au panier.'), 'recovered committed basket');
const uncertainCalls = (await state()).calls.filter(call => call.path.endsWith('/commit')).slice(-3);
assert.equal(new Set(uncertainCalls.map(call => call.body.planId)).size, 1);
assert.equal((await state()).cart.itemCount, cartBeforeLostResponse + 6, 'Lost-response retries must not duplicate products');
console.log('PASS a lost successful response and a 429 retry preserve the same plan without duplicate additions');

await configure({ empty: true });
await ready();
await prepare();
assert.equal(await evaluate(text('Aucun produit n’a été trouvé.')), true);
assert.equal(await evaluate("[...document.querySelectorAll('button')].find(el => el.innerText.startsWith('Confirmer')).disabled"), true);
await configure({ empty: false, available: false });
await navigate();
await wait(text('L’assistant recette est indisponible'), 'unavailable service');
assert.equal(await evaluate("document.querySelector('#recipe-name') === null"), true);
assert.equal(await evaluate("!!document.querySelector('a[href=\"/cart\"]') && !!document.querySelector('a[href=\"/search\"]')"), true);
await configure({ available: true, optionsUnavailable: true });
await navigate();
await wait(text('Impossible de vérifier la disponibilité'), 'options failure');
await configure({ optionsUnavailable: false });
await click('Réessayer');
await wait("!!document.querySelector('#recipe-name')", 'options retry');
console.log('PASS empty results, unavailable AI keeps normal shopping accessible, options failure retry');

await configure({ site: 'Electronics' });
await navigate();
await wait(text('Le panier recette est réservé'), 'other site unavailable');
assert.equal(await evaluate("document.querySelector('#recipe-name') === null && document.querySelector('a[href=\"/recipe-basket\"]') === null"), true);
await navigate('/');
await wait(text('Bienvenue sur Zava'), 'non grocery home');
assert.equal(await evaluate("document.querySelector('a[href=\"/recipe-basket\"]') === null"), true);
await configure({ site: 'Grocery' });
await navigate('/');
await wait(text('Un plat en tête ?'), 'grocery homepage entry');
await navigate('/cart');
await wait(text('Un plat en tête ?'), 'grocery cart entry');
console.log('PASS Grocery-only route, header, home and cart discoverability');

await configure({ site: 'Grocery', available: true, empty: false, planFailures: 0, commitFailures: 0, commitStatus: 503, dropCommitResponses: 0, expiryMs: 600000 });
await ready();
await evaluate("sessionStorage.removeItem('zava-recipe-hidden-session'); sessionStorage.removeItem('zava-recipe-draft'); localStorage.removeItem('zava-recipe-hidden-forever'); localStorage.removeItem('zava-recipe-promotion-dismissed')");
await ready();
await prepare();
assert.equal(await evaluate(text('Produits sélectionnés (4)')), true);
assert.equal(await evaluate(text('16,98')), true);
assert.equal(await evaluate(text('Produits non sélectionnés')), false, 'The cartouche stays out of the way until something is deselected');
await clickLabel('Retirer de la sélection : Pur bœuf haché 15 % MG – Barquette de 350 g');
await wait(text('Produits non sélectionnés (1)'), 'deselected cartouche appears on removal');
assert.equal(await expanded('Produits non sélectionnés (1)'), 'false', 'The cartouche starts collapsed');
assert.equal(await evaluate(text('vous les avez peut-être déjà chez vous')), false, 'Collapsed content stays out of the DOM');
assert.equal(await evaluate(text('Produits sélectionnés (3)')), true);
assert.equal(await evaluate(text('7,18')), true, 'The total only counts the selected products');
await clickLabel('Retirer de la sélection : Tomates concassées');
await wait(text('Produits non sélectionnés (2)'), 'second removal');
assert.equal(await expanded('Produits non sélectionnés (2)'), 'false', 'Removing another product never expands the cartouche');
await click('Produits non sélectionnés (2)');
await wait(text('vous les avez peut-être déjà chez vous'), 'the cartouche only expands on demand');
await clickLabel('Remettre dans la sélection : Tomates concassées');
await wait(text('Produits non sélectionnés (1)'), 'one product left aside');
await clickLabel('Remettre dans la sélection : Pur bœuf haché 15 % MG – Barquette de 350 g');
await wait(text('Produits sélectionnés (4)'), 'restored selection');
assert.equal(await evaluate(text('16,98')), true);
assert.equal(await evaluate(text('Produits non sélectionnés')), false, 'The emptied cartouche disappears');
console.log('PASS deselecting moves a product into a collapsed cartouche, updates the total, and re-selecting restores it');

const pantryCheckbox = "document.querySelector('input[name=\"recipe-include-pantry\"]')";
assert.equal(await evaluate(`${pantryCheckbox}.checked`), true, 'Main and pantry products are suggested by default');
assert.equal(await evaluate(text('Proposer les produits principaux et annexes (condiments, etc.)')), true);
await evaluate(`${pantryCheckbox}.click()`);
await wait(text('Produits non sélectionnés (1)'), 'pantry products leave the selection when the option is unticked');
assert.equal(await evaluate(text('Produits sélectionnés (3)')), true);
assert.equal(await evaluate(text('14,79')), true, 'The total drops the pantry extras');
await click('Produits non sélectionnés (1)');
await wait(text('Huile d’olive vierge extra'), 'the pantry product sits in the unselected cartouche');
await evaluate(`${pantryCheckbox}.click()`);
await wait(text('Produits sélectionnés (4)'), 'ticking the option puts pantry products back in the selection');
assert.equal(await evaluate(text('16,98')), true);
await evaluate(`${pantryCheckbox}.click()`);
await click('Actualiser la proposition');
await wait(text('Produits non sélectionnés (1)'), 'a new preview keeps pantry products aside');
assert.equal(await evaluate(text('Produits sélectionnés (3)')), true);
await evaluate(`${pantryCheckbox}.click()`);
await wait(text('Produits sélectionnés (4)'), 'pantry products return to the selection');
console.log('PASS the main-and-pantry option is ticked by default and unticking moves pantry products into the unselected cartouche');

await clickLabel('Retirer de la sélection : Pur bœuf haché 15 % MG – Barquette de 350 g');
await wait(text('Produits non sélectionnés (1)'), 'deselected cartouche appears again');
assert.equal(await expanded('Produits non sélectionnés (1)'), 'false', 'A reappearing cartouche never remembers a previous expansion');
await click('Produits non sélectionnés (1)');
await wait(text('Ne plus proposer ce produit'), 'hide options appear on the unselected product');
await click('Définitivement');
await wait(text('Produits à ne plus proposer (1)'), 'permanently hidden cartouche');
const cartBeforePartial = (await state()).cart;
const beefLinesBefore = cartBeforePartial.items.filter(item => item.productId === 102).length;
await click('Confirmer et ajouter les produits disponibles');
await wait(text('Les produits de votre recette ont été ajoutés au panier.'), 'partial commit');
const partialCommit = (await state()).calls.filter(call => call.path.endsWith('/commit')).at(-1).body;
assert.deepEqual(partialCommit.excludedItems, [{ productId: 102, variantId: 1002 }]);
assert.equal((await state()).cart.itemCount, cartBeforePartial.itemCount + 4, 'Only the selected products reach the basket');
assert.equal((await state()).cart.items.filter(item => item.productId === 102).length, beefLinesBefore, 'The removed product is never added again');
console.log('PASS confirmation only adds the selected products and reports the removed ones to the API');

await ready();
await prepare();
const afterHide = (await state()).calls.filter(call => call.path.endsWith('/plan')).at(-1).body;
assert.deepEqual(afterHide.excludedProductIds, [102]);
assert.equal(await evaluate(text('Pur bœuf haché 15 % MG')), false, 'A hidden product is never suggested again');
assert.equal(await evaluate(text('Produits sélectionnés (3)')), true);
await click('Produits à ne plus proposer (1)');
await wait(text('Masqué définitivement'), 'hidden scope shown after expanding');
await clickLabel('Reproposer ce produit : Pur bœuf haché 15 % MG');
await wait(text('Produits à ne plus proposer (0)'), 'product suggested again; exclusions stay visible and empty');
await click('Actualiser la proposition');
await wait(text('Produits sélectionnés (4)'), 'product back in the suggestion');
assert.equal(await evaluate(text('Pur bœuf haché 15 % MG')), true);
assert.deepEqual((await state()).calls.filter(call => call.path.endsWith('/plan')).at(-1).body.excludedProductIds, []);
console.log('PASS a permanently hidden product survives a reload, is excluded from new suggestions and can be restored');

await ready();
await prepare();
await clickLabel('Retirer de la sélection : Tomates concassées');
await wait(text('Produits non sélectionnés (1)'), 'session scope cartouche');
await click('Produits non sélectionnés (1)');
await wait(text('Ne plus proposer ce produit'), 'hide options for the session scope');
await click('Pour cette session');
await wait(text('Produits à ne plus proposer (1)'), 'session hidden cartouche');
assert.equal(await evaluate("sessionStorage.getItem('zava-recipe-hidden-session') !== null && localStorage.getItem('zava-recipe-hidden-forever') === null"), true);
await ready();
await prepare();
assert.deepEqual((await state()).calls.filter(call => call.path.endsWith('/plan')).at(-1).body.excludedProductIds, [103]);
await evaluate("sessionStorage.removeItem('zava-recipe-hidden-session'); sessionStorage.removeItem('zava-recipe-draft'); localStorage.removeItem('zava-recipe-hidden-forever')");
await ready();
await prepare();
assert.deepEqual((await state()).calls.filter(call => call.path.endsWith('/plan')).at(-1).body.excludedProductIds, []);
console.log('PASS the session scope is kept separately from the permanent one and does not outlive the session storage');

await ready();
await evaluate("localStorage.setItem('zava-lang', 'en')");
await navigate();
await wait(text('What are we cooking?'), 'English translation');
for (const value of ['National brands', 'Store brands', 'Budget-friendly', 'A mix', 'Suggest both main and pantry products (condiments, etc.)', 'allergens']) assert.equal(await evaluate(text(value)), true);
await evaluate("localStorage.setItem('zava-lang', 'fr')");
await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
await ready();
await screenshot('.recipe-ui-mobile.png');
const width = await evaluate('({ viewport: window.innerWidth, page: document.documentElement.scrollWidth })');
console.log('MOBILE WIDTH', JSON.stringify(width));
assert.equal(width.page <= width.viewport, true, 'No horizontal page overflow at 390px');
assert.equal(await evaluate("document.querySelector('#recipe-name').labels[0].innerText.includes('Votre recette')"), true);
assert.equal(await evaluate("document.querySelector('[role=\"radiogroup\"]').getAttribute('aria-labelledby')"), 'recipe-brands');
await prepare();
await screenshot('.recipe-ui-mobile-preview.png');
const previewWidth = await evaluate('({ viewport: window.innerWidth, page: document.documentElement.scrollWidth })');
assert.equal(previewWidth.page <= previewWidth.viewport, true, 'No horizontal preview overflow');
assert.deepEqual(exceptions, []);
console.log('PASS English/French, labelled controls, mobile form/preview layout and no runtime exceptions');
console.log('All native Chromium mocked-API UI checks passed.');
socket.close();
